### ISSUE TITLE
Randomizer mods crash bl2 on execution?

### ISSUE THREAD

**Issue by Derpythederp** [BLCM/BLCMods#1007]
I am using a macbook pro. Whenever I try to execute pandemonium, the game crashes. Same for CERandomiser. However, the community patch works perfectly fine. Does anyone face the same problemm? Else, could someone suggest a randomiser that may potentially work? (Preferably at least a  weapon/item randomiser)

Note: I tried adding Pandemonium into the community patch, it just causes everything to crash at once

Edit: I have also noticed although my community mod can be executed (as in "exec patch.txt") it doesn't seem to apply changes to the game. It says ULCP 4 is running in console

**Comment by CaptainKoby** [comment]
Running mods on Mac is extremely limited, only very small mods will work.
