### ISSUE TITLE
 Place aurelia (TPS) in place at zero (bl2)

### ISSUE THREAD

**Issue by DuckDuckian** [BLCM/BLCMods#1008]
Pls Place Aurelia skill tree in place of the zero skill tree

**Comment by WubTheGame** [comment]
That would take a lot of work, having to "convert" code from TPS to BL2. That last bit might not be accurate though, I don't have TPS. Take it with a grain of salt.

But yeah, it would take quite a bit of work.

**Comment by CaptainKoby** [comment]
Not possible and nobody is gonna go through the effort to make a "similar" skill tree.
