### ISSUE TITLE
EveryLoot not working.

### ISSUE THREAD

**Issue by Ajpfeiffer** [BLCM/BLCMods#1030]
Howdy folks!

So I copied the file to the correct location, open my game, open the console type in exec EveryLoot.txt and hit enter.

How do I know if the mod is running? All that comes up is a pop up on screen of "ArcherCC says exec EveryLoot.txt"

I logged into my character and ran around for about 15 minutes but all I got was the normal white & green drops.

I am new to modding so thanks for the help!

**Comment by Ethel173** [comment]
https://github.com/BLCM/BLCMods/wiki/Patching-FaQ#12-how-do-i-install-the-ucp--mods

**Comment by apocalyptech** [comment]
Going to close this one out, btw -- if you're still having problems with this after installing BLCMM and looking through the docs/FAQ/etc, stop by the Discord channel, where you'll be more likely to receive timely help.
