### ISSUE TITLE
Invalid file selected issue while selecting my Borderlands 2 exe file

### ISSUE THREAD

**Issue by AmineFellous** [BLCM/BLCMods#1050]
A week ago i downloaded FilterTool and used it to patch a pirated version of Borderlands 2 and worked fine. Yesterday i mistakenly erased the game folder while cleaning some space, so i installed it agin, since i keep the installation files. Given filtertool was in the binary folder, i lost it too so i tryed to download it again, but it have been updated to BLCMM. Now i cant hex the game and patch it becaus whenever i try to select the game exe i got the messege invalid file selected, please try again. Worked fine a week ago with FilterTool, now it doesnt?

**Comment by Ethel173** [comment]
https://github.com/BLCM/BLCMods/wiki/Patching-FaQ#11-what-do-i-need-to-use-the-ucp--mods

closed for piracy
