### ISSUE TITLE
Enemy Randomizer - other players cannot connect to host.

### ISSUE THREAD

**Issue by nt9m** [BLCM/BLCMods#1054]
Maybe its happening, when player trying connect to host dont have required dlc?

Its possible - build "light" version of mod, contents only enemys from main game?

**Comment by CaptainKoby** [comment]
Enemy Randomizer is simply not built for co-op. Your best bet is making people join the host when in Sanctuary, but crashes and timeout are imminent. A "light" version wouldn't fix this because Enemy Randomizer loads all maps in the game every time there's a loading screen.
