### ISSUE TITLE
Borderlands 2 Gameplay start crash

### ISSUE THREAD

**Issue by NellyWhadsDev** [BLCM/BLCMods#1062]
Hey there, I don't see a format here so I'll explain my issue as best I can. It's my first time trying the community patch or any mods whatsoever so please excuse any derps.

**System Info:**
Win 10
GTX1080ti
16gb ram
i7 7700k

**Graphics settings:**
 - Maxed out ereytang; cause I mean, I should be able to right?
 - Anisotropic Filtering: Off
 - Physx Efects: High
 - FXAA: Off

**Installation procedure:**
(Tried multiple times, with various complexities and re-ordering, so here's the "most reccomended" version of the approach I took):
1. Install BL2 + all DLC from Steam
2. Run game and set up my graphics preferences
3. Test game using my OP save profile (Maxed out Zer0, all played through without mods)
4. Exit game and log out of my OS user account (just to make sure everything has stopped running)
5. Log in and copy BLCMM into the BL2 Binaries dir
6. Run BLCMM (v1.1.4.1), enable Hexedit executible and Console Key (~)
7. Note: No patch placed into the binaries folder or enabled using autoexec (it is disabled in the latest release of BLCMM)
8. Run BL2, NOT executing any patch.
9. Create new player and watch history of borderlands cutscene
10. Black screen or faded character choosing screen after loading animation; game freeze; non-responsive

_Alternate path:_
9. Log into existing level 5 character
10. White screen or faded game world screen after loading animation; game freeze; non-responsive

**Notes:** 
 - I've avoided logging into my main level 72 save file to avoid corrupting it; i'd like to continue to avoid that
 - I've tried applying the patch but come accross the same issue; skipping applying the patch was just a way to narrow down the issue
 - Disabling the Hexedit executible and Console Key still leaves the game unplayable
 - Only way to fix the game is to completely uninstall and reinstall the game

Any ideas? Anyone? Pretty please?

**Comment by WubTheGame** [comment]
You can make a backup of your save files. Go to this directory: C:\Users\Landon\Documents\My Games\Borderlands 2\WillowGame\SaveData/*A bunch of numbers*. In here, you will find save files. Find the one for the character you don't want to corrupt, and copy paste it somewhere else, like just outside the saves folder. Afterword, you can safely join in the character without worry.

**Comment by apocalyptech** [comment]
Hello!  If you're still having this issue, it'd probably be best to stop in to the Discord and ask about it in there.  As you've probably noticed, this "Issues" section tends to be pretty ignored.  Closing it out for now!
