### ISSUE TITLE
Java Error; can't open a .txt file (v1.1.5)

### ISSUE THREAD

**Issue by faradaybed** [BLCM/BLCMods#1077]
Hi, 
I recently downloaded everything needed to use the UCP4.1 on BL2, but I couldn't open my Patch.txt file to save my life.
I tried updating both Java and BLCMM (I'm currently on version 1.1.5), but it did not fix the error.
I get a popup saying "Unable to open file: java.lang.NullPointerException"

Thanks in advance for the time someone may take to help me out

**Comment by apocalyptech** [comment]
Hey there - if you're still having this problem, it might be best to hop into the Discord and ask about it in there.  This Issues area isn't very well monitored, and as you can tell, questions like yours can often go for quite awhile without getting addressed.  We're discussing closing down the Issues tab altogether, in fact.

So yeah, if this is still a problem, feel free to stop by the Discord and ask there!  You'll get much quicker help than here.  Closing this one out for now...
