### ISSUE TITLE
CERandomizer

### ISSUE THREAD

**Issue by codolhi** [BLCM/BLCMods#1085]
The CERandomizer works fine with guns but not enemies was wonder if there was steps I could take to fix this.

**Comment by CaptainKoby** [comment]
The CERandomizer is not the Enemy Randomizer. The Enemy Randomizer can be found here https://github.com/BLCM/BLCMods/blob/master/Borderlands%202%20mods/LightChaosman/Enemy_Randomizer.txt

Remember these kinda mods all need to be imported into a single file with BLCMM.
