### ISSUE TITLE
Super Randomizer Multiplayer issues

### ISSUE THREAD

**Issue by FrankReynolds21** [BLCM/BLCMods#1103]
Hey guys I hope this is the right place to post this cause I'm lost, managed to get the super randomizer working finally but it isn't working in co op... the main reason I play borderlands haha. 

Any advice on getting this to work in multiplayer or will it simply not work? thanks.

**Comment by Ethel173** [comment]
Everyone who joins your game needs all story DLCs AND Ultimate Vault Hunter Pack 2
Everyone needs the **same** randomized skill tree files
if HH packs are enabled hostside everyone needs the active HH packs

**Comment by apocalyptech** [comment]
I'm going to go ahead and close this one out so it doesn't hang around like many of our others' do.  If you still need some help on this, it may be worth checking out the Discord!
