### ISSUE TITLE
[REQUEST] Grenade Damage boosted Flakker

### ISSUE THREAD

**Issue by Litchlol** [BLCM/BLCMods#130]
Love the mods here but this is the one thats really missing here, would anyone be kind enough to either show me how or do it for me? tried looking at other peoples code but it goes straight over my head.

Thanks :)

**Comment by Litchlol** [comment]
so looking through a few mod codes where weapons have been moved over to grenade damage i put this code together. afaik it should work but doesnt, any help?

set GD_Weap_Shotgun.FiringModes.Bullets_Shotgun_Torgue_GyroJet:Behavior_Explode_5 DamageSource Class'WillowGame.WillowDmgSource_Grenade'

i feel like it might work but not completely in the way i wanted it to. i think i've somehow got the initial shot before it splits doing grenade damage. but thats no good as it splits instantly. any help at all with this would be highly appricated

**Comment by AngrierPat** [comment]
check the patch for how its done, then dump the flakkers barrel and find its explode behavior (its prob different) and use the same line as you have posted

set FLAKKERBULLETSCODEHERE DamageSource Class'WillowGame.WillowDmgSource_Grenade'
