### ISSUE TITLE
sanity check deletes the gun

### ISSUE THREAD

**Issue by habanerochilly** [BLCM/BLCMods#192]
am i doing something wrong? the other mods are working :(

**Comment by theNocturni** [comment]
Did you activate the code before you went in-game?

**Comment by PyroSoup** [comment]
how do you activate the code

**Comment by Spiderhex** [comment]
despite activating the mods before going in game guns created by the mod Pandemonium by Aaron0000 lose some of their attachments on save loading, it consistently does this

**Comment by FromDarkHell** [comment]
__DISAPPEARING WEAPONS/ITEMS:
If a weapon/item spawns with a barrel/part from a DLC, and the gun/item itself isn't from that DLC, the barrel/part will disappear the next time you load that save file.__ - Aaron000's Pandemonium
