### ISSUE TITLE
[REQUEST] Removing the audio muffle when in a Vacuum

### ISSUE THREAD

**Issue by Ceominus** [BLCM/BLCMods#196]
Borderlands in general has a pretty good sound design, but the muffle in 80% of the game kind of ruins it, is there any way it could be removed?

**Comment by MagicGonads** [comment]
I assume this is not for Borderlands 2?

**Comment by Ceominus** [comment]
No, sorry if this was the wrong location to post this.  First time using GitHub, still a little confused.

**Comment by MagicGonads** [comment]
It's not, that was just a joke since you didn't specify which of the two games!

It's probably not so difficult, ask JimRaven or Forestrike

**Comment by infamous27x** [comment]
Has officially been made https://github.com/BLCM/BLCMods/blob/master/Pre%20Sequel%20Mods/Jim%20Raven/Vacuum%20Sound%20Replacer
