### ISSUE TITLE
[Request]Athena class mod

### ISSUE THREAD

**Issue by Yakuzomoto** [BLCM/BLCMods#259]
Hey guys i really nead a class mod for athena with the skill Elemental Barrage, Storm Weaving, Gathering Tempest, Unrelenting, and Hold the Line.
I am really thankful if someone is able to do one.

**Comment by Yakuzomoto** [comment]
Weapon swap speed would be optimal

**Comment by Kieitrio** [comment]
Ill see what I can do for ya

**Comment by Yakuzomoto** [comment]
Thank you, i really appreciate it.

**Comment by Yakuzomoto** [comment]
This classmod crashes my game, is it because normally Elemental Barrage isn't in any classmod? :/

**Comment by Yakuzomoto** [comment]
Sorry but the game crash after i put on the classmod, is it because of the skill Elemental Barrage? :/
