### ISSUE TITLE
Syntax and content issues (BL1Loot)

### ISSUE THREAD

**Issue by helller** [BLCM/BLCMods#260]
@FromDarkHell, I found couple if issues with mentioned mod, there are syntax errors (misplaced brackets) in SMG Loot pools, also Pistol loot pools are missing whole Dahl section, Vladof and Hyperion gemstone Pistols are dropping like common guns :  
  (
        ItmPoolDefinition = None,
        InvBalanceDefinition = WeaponBalanceDefinition'GD_Weap_Pistol.A_Weapons.Pistol_Hyperion',
        Probability = 
        (
            BaseValueConstant = 0.000000,
            BaseValueAttribute = None,
            InitializationDefinition = **AttributeInitializationDefinition'GD_Balance.Weighting.Weight_1_Common',**
            BaseValueScaleConstant = 1.000000
        ),
        bDropOnDeath = True
    ),
That is all i found for now, (awesome idea for the mod though), I'll keep searching for more incosistencies.

**Comment by helller** [comment]
small correct
      (
        ItmPoolDefinition = None,
        InvBalanceDefinition = **WeaponBalanceDefinition'GD_Aster_Weapons.Pistols.Pistol_Hyperion_4_Diamond',**
        Probability = 
        (
            BaseValueConstant = 0.000000,
            BaseValueAttribute = None,
            InitializationDefinition = **AttributeInitializationDefinition'GD_Balance.Weighting.Weight_1_Common'**,
            BaseValueScaleConstant = 1.000000
        ),
        bDropOnDeath = True
    ),

**Comment by cody712** [comment]
Same issue with the pistol drops, getting a lot of those.
