### ISSUE TITLE
Infiltrator not scaling to level

### ISSUE THREAD

**Issue by NotBlaze** [BLCM/BLCMods#291]
So I started a new play through with Zero and I saw the Infiltrator mod by Coleby. It's supposed to be a sniper that scales its damage to whatever level you are, or so I thought. As I went through regular Vault Hunter mode I noticed that the damage never scaled with me. Can somebody please help me? I'm also using the new v3.1 community patch if that helps in any way.

**Comment by NotBlaze** [comment]
I'm also super new to coding so if there is a simple fix to this I'm sorry. I've been looking over the code for a while and I can't seem to find a fix.

**Comment by infamous27x** [comment]
It is very likely that it scales with level but doesn't display on the card, just how the Sky Rocket works. If you shoot an enemy, does it deal same damage?
