### ISSUE TITLE
I can't use the phaselock mod

### ISSUE THREAD

**Issue by JJR2114** [BLCM/BLCMods#292]

**Comment by theNocturni** [comment]
I'm afraid I need a bit more details
what is the issue that you have with the mod?
how exactly can you not use it?

also one thing to check:
did you correctly merge/add it into the hotfix array as per the instructions?

**Comment by dfsoptimum** [comment]
I have the same issue, I followed the "readme before downloading" for hotfix merging but without success. If I use the UCP FilterTool do I simply need to add your hotfixes like simple mods or are there other steps I'm missing?
