### ISSUE TITLE
How do I combine two mods into one?

### ISSUE THREAD

**Issue by IgnoreMyname** [BLCM/BLCMods#362]
Didn't know where to ask.

I would like the combine the UCP Filter Tool Opportunity relic speed buff with a Afterburner relic ammo regeneration all under the same relic. For example, I would like the speed buff and ammo regeneration to apply to the Opportunity relic so that I won't have to switch relics in-game.

Text files with the codes in the files below.

[Opportunity Speed Buff.txt](https://github.com/BLCM/BLCMods/files/1171536/Opportunity.Speed.Buff.txt)

[Afterburner Ammo Regen.txt](https://github.com/BLCM/BLCMods/files/1171537/Afterburner.Ammo.Regen.txt)

**Comment by Ravenjim** [comment]
Ill give it a look there might be an issue with how much stuff can be assigned to a single relic tho

**Comment by IgnoreMyname** [comment]
Thank you. Although, it doesn't have to be a relic, could be a class mod (Zer0 survivor class mod preferred) or a shield or a grenade....

**Comment by Ravenjim** [comment]
havent managed to merge em somethin is missing. i tried to put em on a com and i failed. ill try a bit more another time

**Comment by IgnoreMyname** [comment]
I appreciate you taking a look. Even if it doesn't work out in the end, thank you for trying.

**Comment by Greeem** [comment]
You could use the FilterTool to load a mod then under Dev Tools select "Add Single mod" and find whatever mod you're looking for.

**Comment by IgnoreMyname** [comment]
Also, if the speed or ammo regen could be applied to a Zer0 com, that would work too. Thing is, I just want to have ammo regen and faster speed at the same time.

Don't mean to sound needy or anything. Appreciate the help.
