### ISSUE TITLE
Can't change Jimmy Jenkins, Vorac, Gee:  Attributes\ Loot pool \ Names by using Spark Values

### ISSUE THREAD

**Issue by Hemaxhu** [BLCM/BLCMods#378]
For some reason it's not working.
I can change it by using Patch in-game with Command: 
set GD_Population_Midget.Balance.LootMidget.PawnBalance_Jimmy PlayThroughs (Blah blah blah...)
But when i do this in | set Transient.SparkServiceConfiguration_6 Values ",GD_Population_Midget.Balance.LootMidget.PawnBalance_Jimmy,PlayThroughs,((PlayThrough=1,DisplayName='J3NKNS MK II',TransformedNames=,OnSpawnCustomizations=,AttributeStartingValues=,CustomItemPoolIncludedLists=,CustomItemPoolList=,MeshMaterial=None))" If i put " in Display Name - Hi CTD.
It's just not working. I tried everything.
Maybe somebody can help me with it?

**Comment by Ravenjim** [comment]
set GD_Population_Midget.Balance.LootMidget.PawnBalance_Jimmy PlayThroughs ((PlayThrough=1,DisplayName=\"WhateverNameYouWant\",TransformedNames=,OnSpawnCustomizations=,AttributeStartingValues=,CustomItemPoolIncludedLists=,CustomItemPoolList=,MeshMaterial=None)

Then make it into Level patch entry with None set as Level

the key part is that hotfix data cannot ready " " thats in the name Thus Nocturni has found that if you put \ before the " it works.

**Comment by Hemaxhu** [comment]
Thanks for the tip.
 But CTD wasn't the main problem. There is no CTD now with \"JimmyName\", but it's still not working in-game by using Spark Values.
I can't change his HP and other stuff by using Transient.SparkServiceConfiguration_6 Values.
Here my text: 
",GD_Population_Midget.Balance.LootMidget.PawnBalance_Jimmy,PlayThroughs,,((PlayThrough=1,DisplayName=\"TestName\",TransformedNames=,OnSpawnCustomizations=,AttributeStartingValues=,CustomItemPoolIncludedLists=,CustomItemPoolList=,MeshMaterial=None))"
I tried to remove  , behind GD_population. Well, i tried many things actually.
But it's works fine when i'm doing it by 
set GD_JimmyJenkins.Character.CharClass_JimmyJenkins AttributeStartingValues #Text# without spark values. (Name this way works too)
 But even if it's working, there is a problem. I have to Exec Patch in every location to get this to work. That's why i want it to work in Spark Values.

**Comment by Ravenjim** [comment]
i think it ll be better if ya DM me on discord about that.. Ya on Shadows server?

**Comment by Hemaxhu** [comment]
Can't contact you on Discord. I just don't have it.

**Comment by Ravenjim** [comment]
My advice would be to look into Herle of UCP then. If you got filter tool its easy to look him up

**Comment by Hemaxhu** [comment]
Nah, still can't figure it out. I tried to do it with Filter Tool support.
(I'm 100% sure PawnBalance, ClassDefinition is correct for Jimmy, others) (Herle example didn't helped me either)
Now i tried to change animation speed : ",GD_GoliathShared.Anims.AnimMotion_LootGoon_Transform,PlayRate,,2.500000" (Spark keys is fine)
Not working.
But some animations are working for some reason. (example: Krieg animations, gaige 'WithClaws' Speed boost, but it worked only when i added >GD_Tulip_Mechro_Streaming<,GD_Tulip_Mechromancer_Skills.Misc.SpecialMove_WithClaws_1st,PlayRate,,1.800000) ).
 Maybe this is what's happening with other animations and PawnBalances.

Btw, Is there any other way to contact you?

**Comment by Ravenjim** [comment]
I mean other than dc.. id guess Facebook
