### ISSUE TITLE
Weapon cards

### ISSUE THREAD

**Issue by Bobooo** [BLCM/BLCMods#41]
@00Schmidt & @DaveRabbit 

Hi,
First of, a big thanks for all of your works but I have a tiny issue with some weapon cards. Instead of having a center point like this "•" I have different symbols. I tried to find a solution by myself by modifying the textfile of those weapons but I can't figure out what to replace.

I join screenshots of those weapons with weapon cards issues, it's not a big deal, it does not prevent me to play but if you could do something to correct this I would thank you, or giving me the way to correct it by myself if you don't want to spend your time doing this. :)

[Weapon cards screenshots.zip](https://github.com/BL2CP/BLCMods/files/951796/Weapon.cards.screenshots.zip)

**Comment by sanscriptum** [comment]
I have the same issue. I'm playing on japanese locale, so that might be the case, but apparently Dave is using some weird symbol that doesn't even show up correctly in my np++.

**Comment by infamous27x** [comment]
Sorry for the late response;

The reasoning of this happening means that your BL2 doesn't really enjoy unicodes and breaks them, replace all the "•"s with a - and it should show a -, but atleast it won't look like weird letters & symbols.
