### ISSUE TITLE
Tweaked mods

### ISSUE THREAD

**Issue by Ravenjim** [BLCM/BLCMods#426]
Just a minute ago a mod was found in the Hub that was a small tweak from another mod made By Dave.
After seeing that mod i went and asked dave if he gave permision for that mod as it was using pretty much ALL the code of Dave's Work and just changing a few numbers.

Turns out Dave was never asked. 
As there was no way of communicating with the "Modder" who uploaded said "Mod" the Mod was deleted.

Point of the post? 
If you are using stuff from other modders be sure to ask their permisions. I do not mean as in just weapon buffs or so but if something is a copy of another mod with a small tweak here and there YOU NEED to get permision of the original Modder. Else the mod will be deleted once noticed and you will be running the risk of losing your Right to post here.

Lets try to not repeat that in the future shall we?
Regards Jim Raven

**Comment by GunsOfAnarchy** [comment]
Jim is there a line of code to adjust the fire rate on these modded guns? I love playing around with these but some of the pre sequel modded guns are super slow I'd love to speed up the fire rate on a few of the guns. Don't worry I'm not reposting them just for my own use.
