### ISSUE TITLE
Skills not changing: Unrecognized class or object: Transient.SparkServiceConfiguration_5

### ISSUE THREAD

**Issue by KrissKhan** [BLCM/BLCMods#501]
Hi peeps,

First thing first, THANKS for all the good job done around. Those patches gives a new breath to both games. I'm really enjoying TPS now.

But well... I ran out an issue, it's all title. Whenever I execute the patch from the full community patch. I got that silly error: `Unrecognized class or object: Transient.SparkServiceConfiguration_5`
Actually I got it twice since there are two entries in the text file. The patch made to make it work out offline doesn't work at all.

I've checked twice video on youtube to make sure I haven't failed the hex-edition. So any ideas why's not working for me ? What am i doing wrong ?

Thanks for reading me.

**Comment by KrissKhan** [comment]
Just figured out this message was poping if your load "too quickly" the patch at start of the game.

Though, skills are still not working on TPS...

**Comment by infamous27x** [comment]
These are hotfixes, they take a bit before loading, TPS works fine for me, did you maybe mess up something?

**Comment by KrissKhan** [comment]
I've reinstalled everything, and for whatever reasons, offline patch is now working (all changes including skills). Online hotfixes are still not working...
I have all DLCs, latest version, running game in french. I give up for now, i'll have fun with the offline patch.

I let open this issue, if someone run in this problem, we might find what to do sharing :)

**Comment by Greeem** [comment]
I think in order for Hotfixes, you need to connect to the internet. And when you first launch your game, you're not connected to the internet.

**Comment by Ravenjim** [comment]
There is an offline version. use that.

**Comment by Jesooo** [comment]
And where i can we find that?

**Comment by Ravenjim** [comment]
https://github.com/BLCM/BLCMods/tree/master/Pre%20Sequel%20Mods/Community%20Patch

**Comment by Ravenjim** [comment]
litterally the same place you found the Normal version.
