### ISSUE TITLE
Help with reduced

### ISSUE THREAD

**Issue by vWolvenn** [BLCM/BLCMods#509]
cant appear to reduce the recoil of my gun, ive played with a few external attributes but no luck

**Comment by infamous27x** [comment]
You can use AttributeSlotUpgrades to go for the easier route, here's some of them. (don't do ridicilous values like I did, just play around.)

`((SlotName="WeaponSpread",GradeIncrease=10000,bActivateSlot=True),(SlotName="AccuracyMin",GradeIncrease=100,bActivateSlot=True),(SlotName="AccuracyMax",GradeIncrease=100,bActivateSlot=True),(SlotName="AccuracyRegen",GradeIncrease=100,bActivateSlot=True),(SlotName="WeaponAccuracyImpulse",GradeIncrease=100,bActivateSlot=True)))`

**Comment by vWolvenn** [comment]
cheers
