### ISSUE TITLE
Relic Overhaul 1.0 - Bone of the Ancients not displaying cooldown reduction?

### ISSUE THREAD

**Issue by Divadus1** [BLCM/BLCMods#514]
Is this intentional? That is, is the relic's additional functionality such that it can no longer display cooldown rate? Image included for reference:

![image](https://user-images.githubusercontent.com/31002196/29267890-b6b54578-813e-11e7-8ce3-c587584e7fdb.png)

**Comment by Orudeon** [comment]
This is 100% not intended. I didn't experience this issue in testing. I'll take a look at it ASAP.

**Comment by Orudeon** [comment]
I can't replicate this issue.

![borderlands2_2017-08-14_12-31-30](https://user-images.githubusercontent.com/16169101/29288260-f4317892-80ec-11e7-9c11-e14999086390.jpg)

I spawned every bone and they all had the right UI and all I had running was UVHMPatchRegular and Relic Overhaul.

The gibbed codes I put in Relic Overhaul are incorrect, though, and I'm about to correct that. Unfortunately that doesn't help the issue. Do you have any other mods that alter relics installed?
