### ISSUE TITLE
Force the game to load an Attribute everywhere ?

### ISSUE THREAD

**Issue by Natsu235** [BLCM/BLCMods#546]
I made a patch using this AttributeDefinition for Pre-Sequel:
"D_Attributes.DamageSourceModifiers.ReceivedAmplifyDamageModifier"

But for some reasons it doesn't want to load every time, for example if I choose to play as Claptrap it will be loaded but not with Nisha.

So, is there a way to force the game to load it everytime ?

**Comment by Ravenjim** [comment]
what are ya trying to achieve with that attribute?

**Comment by Natsu235** [comment]
I made a patch to replace Cryo with Slag. I found another way by using all of these attributes instead:
D_Attributes.DamageSourceModifiers.ReceivedBulletDamageModifier
D_Attributes.DamageSourceModifiers.ReceivedGrenadeDamageModifier
D_Attributes.DamageSourceModifiers.ReceivedLaserDamageModifier
D_Attributes.DamageSourceModifiers.ReceivedMeleeDamageModifier
D_Attributes.DamageSourceModifiers.ReceivedRocketDamageModifier
D_Attributes.DamageSourceModifiers.ReceivedStatusEffectDamageModifier

It's working great but now my problem is I replaced the challenge when you have to deal Ice damage with Amp damage and it's only working when I use the ReceivedAmplifyDamageModifier attribute.

**Comment by Ravenjim** [comment]
try a on demand or patch type hotfix
