### ISSUE TITLE
randomizer enemy mod

### ISSUE THREAD

**Issue by randomname09091** [BLCM/BLCMods#569]
when the loading is done for the mod it goes to a black screen what can i do to resolve this?

**Comment by infamous27x** [comment]
You need to have all DLC, there's an option in the FilterTool to enable the "No HeadHunter" option which should make you be able to play.

**Comment by randomname09091** [comment]
can i have dlc enabled because i only need 3 more dlc

**Comment by infamous27x** [comment]
No, you need all Main DLCs

**Comment by randomname09091** [comment]
What do u mean by all main dlc and so u know I bought the game of the year edition and sorry go all the questions
