### ISSUE TITLE
Help!

### ISSUE THREAD

**Issue by 3328654407** [BLCM/BLCMods#576]
how can i make my modded weapon shots with costs no bullet?
i'm trying to make my own modded weapon
i can't find a something helpful like Tutorial documentation
please help me!  :)

**Comment by B33PB00PJOE** [comment]
You can use WeaponShotCost as your attribute to modify. Making the base value = -1 sould do the trick, as the normal 0.000000 value will just make it cost 1 bullet!

**Comment by 3328654407** [comment]
@B33PB00PJOE oh thank you so much,i always set WeaponShotCost value=0.000000 :)      and do you have a tutorial documentation of how to make the modded weapon?

**Comment by 3328654407** [comment]
@B33PB00PJOE This my code,now i can shot cost no bullet,but my damage is normal
set GD_Weap_Pistol.Barrel.Pistol_Barrel_Vladof_Infinity WeaponAttributeEffects ((AttributeToModify=AttributeDefinition'D_Attributes.Weapon.WeaponDamage',ModifierType=MT_Scale,BaseModifierValue=(BaseValueConstant=10000.000000,BaseValueAttribute=None,InitializationDefinition=None,BaseValueScaleConstant=1.000000)))
set GD_Weap_Pistol.Barrel.Pistol_Barrel_Vladof_Infinity WeaponAttributeEffects ((AttributeToModify=AttributeDefinition'D_Attributes.Weapon.WeaponShotCost',ModifierType=MT_PreAdd,BaseModifierValue=(BaseValueConstant=-1,BaseValueAttribute=None,InitializationDefinition=None,BaseValueScaleConstant=1.000000)))

**Comment by B33PB00PJOE** [comment]
Best bet would be to take a look at other mods in the GitHub and play around with similar values. My Ororo smg alters damage, shot cost, etc too! Here is the attributes for that one:

set GD_Weap_SMG.Barrel.SMG_Barrel_Tediore_Commerce WeaponAttributeEffects ((AttributeToModify=AttributeDefinition'D_Attributes.Weapon.WeaponStatusEffectChanceModifier',ModifierType=MT_Scale,BaseModifierValue=(BaseValueConstant=4.000000,BaseValueAttribute=None,InitializationDefinition=None,BaseValueScaleConstant=1.000000)),(AttributeToModify=AttributeDefinition'D_Attributes.Weapon.WeaponStatusEffectDamage',ModifierType=MT_Scale,BaseModifierValue=(BaseValueConstant=3.500000,BaseValueAttribute=None,InitializationDefinition=None,BaseValueScaleConstant=1.000000)),(AttributeToModify=AttributeDefinition'D_Attributes.Weapon.WeaponDamage',ModifierType=MT_Scale,BaseModifierValue=(BaseValueConstant=-1.000000,BaseValueAttribute=None,InitializationDefinition=None,BaseValueScaleConstant=1.000000)),(AttributeToModify=AttributeDefinition'D_Attributes.Weapon.WeaponShotCost',ModifierType=MT_PreAdd,BaseModifierValue=(BaseValueConstant=1.00000,BaseValueAttribute=None,InitializationDefinition=None,BaseValueScaleConstant=1.000000)),(AttributeToModify=AttributeDefinition'D_Attributes.Weapon.WeaponFireInterval',ModifierType=MT_Scale,BaseModifierValue=(BaseValueConstant=0.250000,BaseValueAttribute=None,InitializationDefinition=None,BaseValueScaleConstant=1.000000)),(AttributeToModify=AttributeDefinition'D_Attributes.Weapon.WeaponClipSize',ModifierType=MT_Scale,BaseModifierValue=(BaseValueConstant=-0.020000,BaseValueAttribute=None,InitializationDefinition=None,BaseValueScaleConstant=1.000000)),(AttributeToModify=AttributeDefinition'D_Attributes.Weapon.WeaponProjectileSpeedMultiplier',ModifierType=MT_Scale,BaseModifierValue=(BaseValueConstant=-5.000000,BaseValueAttribute=None,InitializationDefinition=None,BaseValueScaleConstant=1.000000)),(AttributeToModify=AttributeDefinition'D_Attributes.Weapon.WeaponProjectilesPerShot',ModifierType=MT_Scale,BaseModifierValue=(BaseValueConstant=0.000000,BaseValueAttribute=None,InitializationDefinition=None,BaseValueScaleConstant=1.000000)))

**Comment by 3328654407** [comment]
thank you! :)

**Comment by 3328654407** [comment]
And another question,how can i make a gun with four elementals
