### ISSUE TITLE
Can't use multiple mods with enemy randomizer mod

### ISSUE THREAD

**Issue by Supremesis** [BLCM/BLCMods#585]
Okay so I can get the community patch and the enemy randomizer mod? I've got over 20+ mods in a master text file which I normally use without the randomizer but wanted to play with the randomizer too but it doesn't seem to work with the other mods am I wondering that it's certain mods I might need to remove make it work?

**Comment by empireScum** [comment]
You are trying to run multiple hotfix files. This doesn't work. Instead, merge the files using the filter tool: https://www.youtube.com/watch?v=zJ4qI4U_lE0
