### ISSUE TITLE
Enemy randomizer problem

### ISSUE THREAD

**Issue by don117** [BLCM/BLCMods#605]
Everytime I start enemy randomizer mod after loading a level I get no textures, all I get is a black screen, I can jump, sounds play normally, I can throw granades but they do no bounce on anything, I get the explosion effects, I see weapon lines, but nothing else. I've got GOTY version of a game so it should be ok, it has all the DLCs

**Comment by infamous27x** [comment]
If you don't have Headhunters, install the FilterTool to enable No Headhunter Version

**Comment by don117** [comment]
Tried it too, it's still black and I believe the GOTY has all the DLCs so it should be ok

**Comment by EntityDev** [comment]
If you're sure the GOTY has all DLC, you can try here: [https://github.com/BLCM/BLCMods/issues/616](url)
