### ISSUE TITLE
CatapultFirst.txt

### ISSUE THREAD

**Issue by ChillYourSelf** [BLCM/BLCMods#618]
For whatever reason this mod causes(for zer0 at least) skill tree changes from the community patch to not work. mod: https://github.com/BLCM/BLCMods/blob/master/Borderlands%202%20mods/FromDarkHell/CatapultFirst.txt

**Comment by empireScum** [comment]
In order to run multiple hotfix files, you have to merge them using the filtertool. https://www.youtube.com/watch?v=zJ4qI4U_lE0

**Comment by Ravenjim** [comment]
any hotfix mod will deactivate skill changes UNLESS you merge manual or with filtertool
