### ISSUE TITLE
New to creation, need a little guidance (TPS)

### ISSUE THREAD

**Issue by chaoseclipse01** [BLCM/BLCMods#679]
So, I followed the bare-basic tutorial on how to modify weapons from the Norfleet tutorial and I understand how the basic modding structure works...but I have in mind something a lot more complex. **_A lot more_**. But from all the researching I've done, I can't find the stuff I need to make the weapon I want.

Specifically, how do I go about taking effects from weapons, like the Plunkett, forcing it onto a different weapon and to consume ammo directly from the Ammo Pool on all shots fired instead of just on Criticals, as well as having beam colors that constantly change, and multi-element projectiles?

I'm not asking to have someone generate a weapon for me, I want to learn how to do this myself, but I don't know where to go to learn how do the more complex and crazy stuff that I want to achieve. I've tried staring down files others have made, but I'm not entirely sure what I'm looking at, or looking for, and not getting anywhere or learning anything.

If someone could point me to a tutorial on the more complex aspects of creating custom modded weapons, I'd be extremely grateful.

**Comment by Ravenjim** [comment]
If the weapon you want to pass it into doesnt have anything specific like a generic unique with no special effects then you just copy its behavior into it. If not well. its a bit more complicated and needs some research. In order to keep both effects i mean.

**Comment by chaoseclipse01** [comment]
I was thinking of replacing the Hyperion Longest Yard laser, which is a really generic incendiary Railgun to begin with. I know the command for essentially "replacing" the name of the weapon, as well as modifying most of everything else with the exception of barrel behaviors or special behaviors, or color change commands for laser beams. I already have the object dump info for the stuff I want to use, I just don't have any clue on what to do with the special behaviors, or how to replace parts on guns, or how change laser beam colors.

**Comment by Ravenjim** [comment]
Message me on Discord Jim Raven#3934i think i have some files you could study
