### ISSUE TITLE
a lille help

### ISSUE THREAD

**Issue by zleevz** [BLCM/BLCMods#714]
hi there fellow Vault Hunter,s , so i,m stil , like everyone enjoying the Patches & wonderfull Mod,s this Community makes , now i recently found 2 Mods  " Shield Behavior Overhaul " &  " Shield Stat Tweaks " , wich are made by Orudon & other Modder,s

when i read the file of Shield Stat Tweaks Mod , there is a line wich states  : must pick a Torgue capacitor in the Torgue section or this mod will default to the UCP .

So i have no cleu what this instruction exactly means  .

my 2nd Question is i,m seeing in the File of the Shield Behavior Mod , that it is recommended to use LightChaosman's Filter Tool to instal it , will it not work if i simply add it to the game Via Txt /console ?

a Suggestion/Tip would be much appreciated!, apologies i,m not a Borderlands Modder , nor my know how isn,t that great about it .

these are the files mentioned 

[https://github.com/BLCM/BLCMods/blob/master/Borderlands%202%20mods/Orudeon/Shield%20Behavior%20Overhaul%201.2a.txt](url)

[](url)https://github.com/BLCM/BLCMods/blob/master/Borderlands%202%20mods/Orudeon/ShieldStatTweaks1.2.txt[](url)

**Comment by Orudeon** [comment]
With respect to 'defaulting to the UCP version of the torgue capacitor', use the filter tool, it'll make more sense that way. It lets you toggle which version you use, for a variety of things.

For your second question, please just use the filter tool, it will make merging the hotfixes with the rest of the hotfixes that the patches load much simpler. You can access the filter tool by going here: https://www.youtube.com/watch?v=zJ4qI4U_lE0
