### ISSUE TITLE
Cutscene Disabler questions

### ISSUE THREAD

**Issue by habanerochilly** [BLCM/BLCMods#746]
My cutscene disabler rarely works. maybe i execute it at the wrong time. (when do i activate it? title screen or ingame?)
or maybe it's because i use german language?
does anyone know?

**Comment by amaterasu2011** [comment]
I have this same problem.

**Comment by Fogrits** [comment]
Cutscene Disabler only works on Sanctuary's "introduction" cutscenes, according to the mod's code.

**Comment by infamous27x** [comment]
Cutscene Disabler only disabled pre-rendered cutscenes, which is sanctuary and dlc introduction cutscenes.
