### ISSUE TITLE
A few questions regarding some TPS Mods and their function

### ISSUE THREAD

**Issue by FarztRookie** [BLCM/BLCMods#749]
Hello Guys,
first of all, sorry for creating a thread just to aks questions about some mod-functions, since I am no coder myself. I´m very thankful for this platform and for the people that are uploading these codes for modding, especially the Community Patch, it´s really more fun with it. 
Exactly for that reason I am suprised that some of theses mods have no description of what they do in game whatsoever. For example the "NoRespawnLimit"-mod from "FromDarkHell", none of his mods have descriptions or readme-files which summarize what they do. It´s really hard for a non-coder to see through this. Do I miss something or not seeing the description?

I would be really thankful, if somebody would explain to me, what some of these mods are doing like the "NoRespawnLimit"-mod and the "Moonrunes"-mod, they sound interesting.

**Comment by Ravenjim** [comment]
We try to keep a small info section in each mod. If its not visible at first maybe its easier to see with filter tool. That said imma notify Dark about it.

**Comment by FarztRookie** [comment]
Yeah Thanks, I know, most of them have an info section. And thanks for notifying him, haven´t tried some of his mods yet, because I wouldn´t know where to watch for their functioning; what does the "NoRespawnLimit"-mod do ?

**Comment by Ravenjim** [comment]
@FromDarkHell  bump
