### ISSUE TITLE
FilterTool on Linux

### ISSUE THREAD

**Issue by Tixle** [BLCM/BLCMods#773]
Heya, so I'm having some issues with the filtertool, with the help of someone I managed to figure out how to launch it under linux. With java -XX:MaxHeapFreeRatio=50 -jar .steam/steam/steamapps/common/BorderlandsPreSequel/steamassets/binaries/FilterTool.jar but upon getting it to launch I'm greeted with this https://imgur.com/a/S5SKG . I wanted to ask if this was an known thing or if there's a workaround for it so I can patch TPS, I have BL2 figured out, I just have to manually exec the patch.txt which is easy enough. But with TPS, it has autosay on and I can't for the life of me get that disabled on my own, hence the use of the filter tool.

Thanks in advance!
~Tixle

**Comment by tenshinoshi** [comment]
As far as I can tell there is no work around yet. The Filter Tool needs to have Linux/macOS support added, but the likelihood of that happening is a bit low. I was able to edit the engine myself but.... I cannot find the youtube video I found that described the edit I used.

**Comment by apocalyptech** [comment]
Thanks for the tip about launching with the "-XX:MaxHeapFreeRatio=50" argument to get this to launch on Linux -- I'd been wondering why it would just exit right out to the terminal.

As regards to getting this to work on TPS, I did eventually dig up exactly how to patch TPS to allow non-autosay console commands.  It involves a little work but all the info needed is contained in these two reddit posts and (go figure) the video description of one YouTube video:

https://www.reddit.com/r/Borderlands/comments/5y35js/community_patch_for_linuxand_probably_mac/
https://www.reddit.com/r/Borderlands2/comments/42vs9v/developer_console_commands/
https://www.youtube.com/watch?v=pPm8OMK3WaE

The first post is probably how you got it to work on B2 -- there's a handy `engine.upk` file you can download and replace, which does the magic for you.  There's no handy `engine.upk` for TPS (that I can find, anyway), so you have to patch your own.  The second reddit link has the instructions basically (though the post itself only talks about B2), and the hex-editing values you need to look for are in the video description of that youtube video (I haven't found them online anywhere else yet).

Briefly:
1) Rename or move `engine.upk` and `engine.upk.uncompressed_size` so they're out of the way
2) Download "Unreal Package Decompressor" (`decompress.zip` -> `decompress.exe`) from http://www.gildor.org/downloads
3) Run decompress.exe against engine.upk using Wine: `$ wine decompress.exe engine.upk` - that will create a directory named `unpacked` with a decompressed `engine.upk` inside
4) Use a hex editor on that decompressed `engine.upk` and change the two locations where there are the bytes `1B 0A 49` with `1B A2 14` *(this is the info acquired from that youtube vid)*.  I just use a simple console hex editor named "hexedit": http://rigaux.org/hexedit.html
5) Put your patched `engine.upk` in place of where the original was.
6) Edit your `willowinput.ini` as per usual to enable a console hotkey

So... yeah!  Not as straightforward, but that'll get things patched for TPS.

(FWIW, and a little bit back on track for this bug, I'm personally not bothered that FilterTool can't do the actual patching on Linux.  It can still be used to manage the Patch.txt file itself, which is its main benefit, IMO)

**Comment by c0dycode** [comment]
Pre-Patched TPS upk's can be found on my repo here:
https://github.com/c0dycode/BLTPSModStuff/blob/master/TPS%20Set%20and%20Say-Patched%20UPKs.zip
