### ISSUE TITLE
patch and more chest not working together 

### ISSUE THREAD

**Issue by goodengrish757** [BLCM/BLCMods#784]
iv just installed the community patch and the more chest mod and i can get them to work one at a time but not both. i have created a master file to run them both but it only ends up running one

**Comment by infamous27x** [comment]
Alright bud, you probably never watched any of Shadow his tutorials, which is fine, so here's a full instruction.

Step 1: Go to the FilterTool video and install FilterTool (https://www.youtube.com/watch?v=zJ4qI4U_lE0)
Step 2: Watch the FilterTool video.
Step 3: Done.

If you're still confused and can't understand him

Step 1: Put the FilterTool.jar in the Binaries folder, same place where you put your patch.txt
Step 2: Open FilterTool
Step 3: Do whatever options, if it says "Open PatchFilter etc..." go to File > Open File and double click patch.txt
Step 4: Go to Developer Tools > Add Single Mod and double click on the More Chest Mod.
Step 5: File > Save Patch

There you go.

**Comment by goodengrish757** [comment]
awesome that worked thanks
