### ISSUE TITLE
Issue with the CERandomizer

### ISSUE THREAD

**Issue by Frost2779** [BLCM/BLCMods#799]
Any time that I try to lead up the patch in my game I get errors saying 
`Unrecognized class or object GD_Aster_Weapons.Snipers.SR_Maliwan_4_Aquamarine:WeaponPartListCollectionDefinition_306

Unrecognized class or object GD_Aster_Weapons.Snipers.SR_Maliwan_4_Aquamarine:WeaponPartListCollectionDefinition_306

Unrecognized class or object GD_Aster_Weapons.Snipers.SR_Maliwan_4_Aquamarine:WeaponPartListCollectionDefinition_306

Unrecognized class or object GD_Aster_Weapons.Snipers.SR_Maliwan_4_Aquamarine:WeaponPartListCollectionDefinition_306

Unrecognized class or object GD_Aster_Weapons.Snipers.SR_Maliwan_4_Aquamarine:WeaponPartListCollectionDefinition_306`

Furthermore, after removing those entries in attempt to get everything to at least run I got a similar issue with the errors
`Unrecognized class or object GD_Aster_Weapons.Snipers.SR_Maliwan_4_Aquamarine:WeaponPartListCollectionDefinition_253

Unrecognized class or object GD_Aster_Weapons.Snipers.SR_Maliwan_4_Aquamarine:WeaponPartListCollectionDefinition_253

Unrecognized class or object GD_Aster_Weapons.Snipers.SR_Maliwan_4_Aquamarine:WeaponPartListCollectionDefinition_253

Unrecognized class or object GD_Aster_Weapons.Snipers.SR_Maliwan_4_Aquamarine:WeaponPartListCollectionDefinition_253

Unrecognized class or object GD_Aster_Weapons.Snipers.SR_Maliwan_4_Aquamarine:WeaponPartListCollectionDefinition_253`

**Comment by FromDarkHell** [comment]
This is a problem on GBX's end.
There used to be a bug where Aquamarines weren't able to spawn at all and they fixed it by creating a new partlistcollectiondefinition.
