### ISSUE TITLE
Runaway Firing on ClassicSledgeV3

### ISSUE THREAD

**Issue by cyberpapa** [BLCM/BLCMods#800]
I noticed that at times the gun will go through about 20 rounds before it stops auto-firing. Not a problem for my gunzerker though. I've unequipped and reequipped but it persists (I run the unofficial patch prior to running ClassicSledgeV3.txt).
Fabulous work. Your code is spotless.

**Comment by infamous27x** [comment]
It's because the burst is set at 100 to replicate the BL1 10000% Burst Fire, this is intended.
