### ISSUE TITLE
ucp offline

### ISSUE THREAD

**Issue by CanadianGuy12** [BLCM/BLCMods#805]
I'm not sure what I am doing wrong but when I try to load the offline I get 4 unrecognized classes and it wont load/work

**Comment by infamous27x** [comment]
Which 4 to be exact? Also, don't use offline if you don't actually use the offline patch

**Comment by CanadianGuy12** [comment]
Unrecognized class or object   GD_Iris_Weapons.Shotguns.sg_Hyperion_3_SlowHand:WeaponPartListCollectionDefinition_267
Unrecognized class or object CollectionDefinitionbject GD_Orchid_RaidWeapons.Shotgun.Spitter.Orchid_Seraph_spitter_Balance:WeaponPartListCollectionDefinition_283

GD_Lobelia_Weapons.Shotguns:SG_Tourge_6_Carnage:WeaponPartListCollectionDefinition_273

GD_Aster_RaidWeapons.Shotguns.Aster_Seraph_Omen_Balance:WeaponPartlistColletionDefinition_224

**Comment by infamous27x** [comment]
This is a known issue and we currently have no fix, sorry.
