### ISSUE TITLE
Filter tool causing crash

### ISSUE THREAD

**Issue by Ravenous212** [BLCM/BLCMods#811]
The game can launch fine as long as it's not hex edited, after hex editing with the filter tool it won't even launch the game, no crash log or error, tried with -nolauncher and -nostartupmovies and neither help to workaround this issue either, tried verifying files, re-downloading the filter tool, patch and even a full re-install of borderlands 2, if anyone can help it would be greatly appreciated.

Windows 10 if that helps, game locked up and was forced to use task manager, leading to the current situation.

**Comment by infamous27x** [comment]
Do you use the Steam version or a torrented version?

**Comment by Ravenous212** [comment]
Steam version, GOTY with all DLC except skin packs as well, if there's any other information you need just say so...

**Comment by Ravenjim** [comment]
There are two Launch options
One with the thing that makes you sellect settings before playing and the one that opens the game instnatly
Try the options one and press Default - > apply on settings

**Comment by Ravenous212** [comment]
Unfortunately that didn't work either, as soon as the game is about to start with the Borderlands 2 popup banner, it crashes... As said previously it doesn't give any crash log or error, just closes without anything further.

**Comment by Ravenous212** [comment]
Found the cause, java required an update which was causing the crash, it's all working fine now!
