### ISSUE TITLE
Most of patch doesn't work

### ISSUE THREAD

**Issue by Zyrosushi** [BLCM/BLCMods#812]
From what I can tell, the only thing working with the patch text file I've got is the moonstone auto pickup. I've tried downloading a new patch text file, but nothing seems to be working. What is causing this?

**Comment by infamous27x** [comment]
Do you play offline or not?

**Comment by Zyrosushi** [comment]
I do not. Should I?

**Comment by infamous27x** [comment]
No, do any errors show up on the console? if so please send a screenshot, if not, do the following;

Open your patch.txt in a notepad
Search for Transient.SparkServiceConfiguration_ <- should be at the end of the notepad file, can also just CTRL + F this
If it's _6, change it to _5, if it's _5 change it to _6, do this to BOTH, there's 2 in the file, re-execute in the Main Menu after you save changes.

**Comment by Zyrosushi** [comment]
I'll try it later and let you know! Thanks in advance

**Comment by Zyrosushi** [comment]
Now my FilterTool won't open because of some error, I'm sending the log attached to this.
![untitled](https://user-images.githubusercontent.com/35531154/35062930-8074e55a-fbbd-11e7-93fb-a7e389da703d.png)
I could still run the patch, since it still hex edited my file, but there were a lot of 'unrecognized' classes or objects, too many to fit on the screen, so I didn't take a screenshot of it.

**Comment by infamous27x** [comment]
Do you have all DLC? If not, that's why.

**Comment by Zyrosushi** [comment]
Unless a new DLC was released in the past week, yes, I do have all of them.

**Comment by infamous27x** [comment]
@Ravenjim Could you help this man? Not a TPS player, so.

**Comment by Ravenjim** [comment]
Ill need a bit of info.
Are you on windows. If not i cannot help ya as i dont have linux or mac
Are you execing on the Continue screen
Did ya actually do the Hex edits or did you only enable console

**Comment by Zyrosushi** [comment]
I am on Windows.
I am execing on the Continue screen, I think.
I used the FilterTool to hex edit, and it said it was successful.
I have all DLCS.

**Comment by Ravenjim** [comment]
send a screen of the error plz

**Comment by Zyrosushi** [comment]
Since I didn't know which you meant, the in-game error related to the patch or the FilterTool error, I'm sending both.

![error1](https://user-images.githubusercontent.com/35531154/35163693-8e3975d8-fd3f-11e7-8358-32723ee1507b.jpg)

![error2](https://user-images.githubusercontent.com/35531154/35163702-92587588-fd3f-11e7-9b20-b68a5795c7b8.jpg)

![error3](https://user-images.githubusercontent.com/35531154/35163704-94331de0-fd3f-11e7-8295-33dfa1faeae7.jpg)

![error4](https://user-images.githubusercontent.com/35531154/35163717-98ae0fba-fd3f-11e7-9ef5-ae4855156c3d.jpg)

**Comment by Ravenjim** [comment]
If you have Discord i may have some ideas to help ya out. message me at Jim Raven#3934

**Comment by Ravenjim** [comment]
Allright Talked on Discord With Zyro problem Fixed. For others who may see that ALWAYS PRESS VIEW RAW Then RIGHT CLICK SAVE AS on either the Text or the URL.
