### ISSUE TITLE
Patch Download Issue

### ISSUE THREAD

**Issue by Shyler123** [BLCM/BLCMods#813]
Whenever I try to download the Pre-Sequel Community patch it takes me to the same link as the RAW file

**Comment by infamous27x** [comment]
https://www.dropbox.com/s/kxvf8w3ul4zuh93/Patch.txt?dl=0

**Comment by Shyler123** [comment]
i was having this issue with the Pre sequel 2.1 sorry i forgot to specify

**Comment by infamous27x** [comment]
https://github.com/BLCM/BLCMods/blob/master/Pre%20Sequel%20Mods/Community%20Patch/Community%20Patch%202.0/Patch

Just replace your patch.txt with this one, should be 2.1

**Comment by Ravenjim** [comment]
i dont understand whats the problem press view raw and save as
