### ISSUE TITLE
No Executable File on (MAC)

### ISSUE THREAD

**Issue by exit-ium** [BLCM/BLCMods#815]
I've watched multiple videos about tutorials for installing modded weapons, and all of them lead down the same path.I've done all the steps prior to being able to enable the weapons in the game, but the only problem is the executables. On tutorials, it says that is in my Win32 folder, but there is no file there. Would I just need to create a file name for that? Also, if I did get that file, what would I have to do to be able to use the exec. commands in console? I'm on the MAC platform so it's relatively different from Windows. Instead of Hex Editor, I use software called Hex Fiend, which I believe serves the same purpose but I'm not sure how to properly use it. I'd be nice to have some guidance into knowing what to do to be able to use these modded weapons for a MAC platform. 
(Also, if this isn't the problem, I wouldn't really know where else to start)

**Comment by c0dycode** [comment]
Mac/Linux need to Hexedit/replace the Engine.upk. If you need that for BL2, the FilterTool should have them included.

For TPS you can download them here:
https://github.com/c0dycode/BLTPSModStuff/blob/master/TPS%20Set%20and%20Say-Patched%20UPKs.zip
