### ISSUE TITLE
[request] faster container opening animation for Pre-Sequel?

### ISSUE THREAD

**Issue by L-a-n-g-o-l-i-e-r-s** [BLCM/BLCMods#823]
Hi there,

I was wondering if it was possible to speed up the opening of containers, I have always felt that the containers which rather than blowing off into space open far too slow, it's very grating on the nerves. (This is for the Pre-Sequel).

Sorry if we're not supposed to ask this here, but I think it's a neat idea. Unfortunately it's over my head, so if someone with some know how gets the time and inspiration to do it, that would be really neat. I imagine a lot of people would like that mod. I'd say that it's one of the biggest annoyances to me personally.

**Comment by apocalyptech** [comment]
Hello!  This is something that's actually been on my TODO list for awhile, though I have yet to actually get around to it.  We're closing out this whole "Issues" section, so I'm closing out this issue too -- this was never the best-monitored of areas.  If you're interested in trying your hand at it, feel free to stop by the Discord, and if I ever get around to doing this mod anyway, it'll be announced in there as well.
