### ISSUE TITLE
Gaige reload op? 

### ISSUE THREAD

**Issue by Dylan343** [BLCM/BLCMods#834]
I randomly get an evil smasher like effect after reloading which buffs the mag size and damage making all my weapons op until I reload one of them. 

My mods 
Patch.txt
GaigeReworkV1.1.txt
MoreChests.txt
MashersV4.txt
CobraPLus.txt
DefilerV3.txt
InFIXity.txt
BetterBones.txt
LuckCannon.txt
InfinityBeyond.txt
FarmHouse.txt
MoreChubbies.txt
MoreRareMidgets.txt

**Comment by Dylan343** [comment]
When it procs the skill on the bottom right shows up, I don't know what its called 

https://steamuserimages-a.akamaihd.net/ugc/911287766750198597/91E6203E89B86DF446C4571B2BF727A6081D1262/

**Comment by Meimetro** [comment]
This simbol is the grog nozzle effect for multiplicate your projectiles.

**Comment by Ethel173** [comment]
is [this](https://github.com/BLCM/BLCMods/blob/5a91f5699bc56bb76c10b69f35b20487b719ea8b/Borderlands%202%20mods/AngrierPat/Skill%20Changes/Custom%20Skills/Smashed%20Reload) in your patch?

**Comment by Dylan343** [comment]
It is now

**Comment by Dylan343** [comment]
It still seems overpowered is it meant to be used in uvhm only?

**Comment by Ethel173** [comment]
no i was asking if that was already in your patch
since AFAIK that would be the only reason that would be happening
unless you have a mod that restores the evil smasher to pre nerf status
