### ISSUE TITLE
unrecognized class or object transient.SparkServiceConfiguration_6 error

### ISSUE THREAD

**Issue by ObamaStoleMyBike** [BLCM/BLCMods#854]
I have things like the UCP and random mods and they work fine but now every time I try getting a new mod this pops up in my console when I execute it (unrecognized class or object transient.SparkServiceConfiguration_6). Can someone help me fix this?

**Comment by Meimetro** [comment]
Spark services are hotfixes...this is something with the servers...wait at least 10 seconds to exec the patches...maybe solve this

**Comment by ObamaStoleMyBike** [comment]
Yeah it still didnt work and I have no idea why. Could the mods be conflicting each other?

**Comment by Meimetro** [comment]
Onlu care about spark services errors...must mods change things who another mods already do...You may pay attention to load order.

**Comment by Ethel173** [comment]
this is due to the fact that it takes a little bit of time to pull the hotfix system from GBX
literally nothing we (as modders) can do to fix this

just wait a little bit longer and exec whatever the file name is again
