### ISSUE TITLE
Pre-sequel Patch not working

### ISSUE THREAD

**Issue by bambiesti** [BLCM/BLCMods#855]
so my community patch stop working out of nothing, no skill changes or else pls someone help me!
![image](https://user-images.githubusercontent.com/37922892/38126048-eac8ff00-33a2-11e8-912b-ce892039d68b.png)
![image](https://user-images.githubusercontent.com/37922892/38126061-fd47076c-33a2-11e8-964a-87223b6e9258.png)

**Comment by infamous27x** [comment]
If you use FilterTool, please make sure your patch is on Offline mode.

If not, search for Transient. (CTRL+F) in notepad and make sure the _6 is changed to _0, there are 2 Transient.Spark blabla (don't remember the full name), make sure both are changed to _0

**Comment by bambiesti** [comment]
Thank you man, it was the offline mode.
