### ISSUE TITLE
Cutscene Disabler

### ISSUE THREAD

**Issue by KnockadASF** [BLCM/BLCMods#857]
I've downloaded your cutscene disabler and it doesnt seem to work. I exec it everytime in different ways trying to find out if om doing it wrong or not... Could you please help.

**Comment by infamous27x** [comment]
Merge it with the FilterTool

**Comment by Ethel173** [comment]
https://github.com/BLCM/BLCMods/wiki/UCP-Filter-Tool#importing-mods
