### ISSUE TITLE
[request] Renaming Entities

### ISSUE THREAD

**Issue by smithxn** [BLCM/BLCMods#860]
This isn't really an issue but is a request for help as i can't think of another way to do it.
This is directed at anyone that knows how to rename entities, (especially from @Ethel173 ). I saw the mod DerpTrap by @Ethel173 and i thought it was really cool that he renamed an in-game entity. I was just wondering if anyone else (or they) could tell me how to do this for other entities such as Axton's Sabre Turret as i have looked around GitHub and on the internet for the code of in-game names, to no avail. If there is like a list somewhere or a way to find the code for in-game entities I would extremely appreciate it, thanks ^_^.

**Comment by Ethel173** [comment]
as a level `None` hotfix
 `set GD_Balance_SkillActors.Turret.Pawn_Balance_Scorpio PlayThroughs ((PlayThrough=1,DisplayName='Sabre Turret',TransformedNames=,OnSpawnCustomizations=(Behavior_AttributeEffect'GD_Balance_SkillActors.Turret.Pawn_Balance_Scorpio:Behavior_AttributeEffect_0'),AttributeStartingValues=,CustomItemPoolIncludedLists=,CustomItemPoolList=,MeshMaterial=None))
`

**Comment by smithxn** [comment]
@Ethel173 Sorry i'm really stupid but this is really hard for me to understand hehe. I really am sorry that i don't understand coding well so i'm going to say this as best as i can. Firstly, i don't know what it means when you say "as a level None hotfix" because i don't know like anything coding. Secondly, it would be really awesome if you could tell me where you got the code from, if you somehow unpacked it from the game files, then don't worry about this one. Thirdly, thanks for responding i really appreciate your effort to help, unfortunately i'm to thick to understand it. 
P.S Is your profile pic Yuuki? cuz it looks like her, and again thanks for helping me.

**Comment by smithxn** [comment]
Sorry i'm really stupid but this is really hard for me to understand hehe. I really am sorry that i don't understand coding well so i'm going to say this as best as i can. Firstly, i don't know what it means when you say "as a level None hotfix" because i do't know much about coding. Secondly, it would be really awesome if you could tell me where you got the code from, if you somehow unpacked it from the game files, then don't worry about this one. Thirdly, thanks for responding i really appreciate your effort to help, unfortunately i'm to thick to understand it.

**Comment by smithxn** [comment]
@Ethel173 Sorry to tell you but i'm stupid and i don't understand coding well. Firstly i don't understand what you mean when you said "as a level None hotfix" because as b4 mentioned i don't know what i'm doing. Secondly, i was wondering where you got the code from and the code for deathtrap, so in future i might be able to rename other characters in my game for my own personal use, if u got the code through unpacking the game, then don't worry about this one. Thirdly, thank you for responding i really appreciate that your trying to help, unfortunately i'm a bit thick-headed to understand without further information.
P.S Is your profile picture Yuuki? because it looks like them. Also idk what's going on with Github or my computer right now but it's saying someone comments i did are there and i can't see them there and a bunch so i had to rewrite the one that your reading now. And again, really, REALLY thanks.

**Comment by Ethel173** [comment]
typically we use https://github.com/BLCM/BLCMods/wiki/UCP-Filter-Tool to dump objects we can edit see https://github.com/BLCM/BLCMods/wiki/Tutorial:-Mod-Basics as its not merged into the first page at the moment, although some prefer to use the in game console as not everything is in the filter tool yet.

For a basic tut for what a hotfix is see https://github.com/BLCM/BLCMods/wiki/Tutorial%3A-Hotfix-Data
and thirdly yes it is, rip :(

**Comment by smithxn** [comment]
Thanks really appreciate all of your help, your awesome ^_^.
