### ISSUE TITLE
Listing of objects / More in depth info

### ISSUE THREAD

**Issue by cmdrbarneyfive** [BLCM/BLCMods#864]
I'd like to add my own changes/edits in the UCP patch.txt file. Specifically, I'd like to have Boll drop the Lady Fist. I've made some of my own changes by using the existing changes as an example. My problem is that when I want to do something completely new, I don't have a way to view the internal objects, classes, collections, enumerations and other programmatic objects.

For instance, here is where the patch adds the Lady Fist to **Saturn**...
set `GD_CustomItemPools_MainGame.Assassin.HyperionCommon` BalancedItems 
(
    (
        ItmPoolDefinition = None,
        InvBalanceDefinition = WeaponBalanceDefinition'GD_Weap_Pistol.A_Weapons_Unique.Pistol_Hyperion_3_LadyFist',
        Probability = 
        (
            BaseValueConstant = 0.000000,
            BaseValueAttribute = None,
            InitializationDefinition = AttributeInitializationDefinition'GD_Balance.Weighting.Weight_1_Common',
            BaseValueScaleConstant = 1.000000
        ),
        bDropOnDeath = True
    )
)

set `GD_Population_Loader.Balance.Unique.PawnBalance_LoaderGiant` DefaultItemPoolList  
(
    (
        ItemPool = ItemPoolDefinition'GD_ItempoolsEnemyUse.Shields.Pool_Shields_Standard_EnemyUse',
        PoolProbability = 
        (
            BaseValueConstant = 1.000000,
            BaseValueAttribute = None,
            InitializationDefinition = None,
            BaseValueScaleConstant = 1.000000
        )
    ),
    (
        ItemPool = ItemPoolDefinition'GD_Itempools.Runnables.Pool_Talos',
        PoolProbability = 
        (
            BaseValueConstant = 0.000000,
            BaseValueAttribute = AttributeDefinition'GD_Itempools.DropWeights.DropODDS_BossUniques',
            InitializationDefinition = None,
            BaseValueScaleConstant = 1.000000
        )
    ),
    (
        ItemPool = ItemPoolDefinition'GD_CustomItemPools_MainGame.Assassin.HyperionCommon',
        PoolProbability = 
        (
            BaseValueConstant = 0.000000,
            BaseValueAttribute = AttributeDefinition'GD_Itempools.DropWeights.DropODDS_BossUniqueRares',
            InitializationDefinition = None,
            BaseValueScaleConstant = 1.0
        )
    )
)

I could of course copy/paste/edit this existing bit of code but my problem is the two objects after the "SET" statements.
GD_CustomItemPools_MainGame.Assassin.HyperionCommon
GD_Population_Loader.Balance.Unique.PawnBalance_LoaderGiant

I'd like to know of a tool/process/procedure that would allow me to see the corresponding information for Boll. Really, I'd like to be able to see this kind of info for everything. Can someone help?

Thanks.

**Comment by Ethel173** [comment]
https://github.com/BLCM/BLCMods/wiki/UCP-Filter-Tool has an object explorer, https://github.com/apocalyptech/ft-explorer also works if you prefer it over filter tool

**Comment by cmdrbarneyfive** [comment]
Thank you for your help! I do have the UCP FilterTool installed and saw the Object Explorer. I couldn't find what to put in the "Object to dump" text box though.
