### ISSUE TITLE
[request] Ray Gun like the one from COD Black Ops

### ISSUE THREAD

**Issue by calcprogrammer** [BLCM/BLCMods#869]
Hey modders, I was wondering if it was possible to create a mod of any pistol with corossive Ray gun firing patterns, but also has the look of the Ray gun from black ops. Thanks for your time, and stay awesome u guys ☺
@DaveRabbit  @ItsCoolDood

**Comment by CaptainKoby** [comment]
Yes.

**Comment by CaptainKoby** [comment]
Yes, the question is though if you want to make that yourself or have somebody else make that for you.

**Comment by calcprogrammer** [comment]
I dont know how to make mods, so i would love if someone would make that for me, of course if u aren't busy. Really appreciate the help guys :)

**Comment by calcprogrammer** [comment]
^Could anyone make this for me?^

**Comment by ItsCoolDood** [comment]
I don't really do mods anymore, but I guess I could give it a go, just give me a couple days, and also somewhere I can actually contact you directly.

**Comment by calcprogrammer** [comment]
@ItsCoolDood well i have an email, its calcprogrammer02@gmail.com, thanks for taking the time for this man, rlly appreciate it :)

**Comment by calcprogrammer** [comment]
You can contact me anytime on gmail when your done, and send me the mod, thanks again :)

**Comment by NB55NB** [comment]
Hmm this looks like you just need to change the projectiles on a weapon to railgun's projectiles then disable weaponshotcost. I'm not sure how to edit the parts to be specific so the looks seems like the hardest part of this project.

**Comment by calcprogrammer** [comment]
Well, it should be a mod of the lady fist, it should look kinda like a corrosive lady fist but with extra 
4 e-tech "side wing things", not necessarily infinite ammo, just a ray gun projectile pattern

**Comment by calcprogrammer** [comment]
ItsCoolDood has kindly made this gun for me, thanks for all the help guys, especially @ItsCoolDood  ;D
