### ISSUE TITLE
Trying this again. I can't click or do anything in the filter tool. Any help?

### ISSUE THREAD

**Issue by DieForSly** [BLCM/BLCMods#874]
As I said the title says it all. When I try to click or check/uncheck any items on the filter tool it doesn't let me click on them.

**Comment by SommerXV** [comment]
Is this for any category? If not, you're probably clicking on a Mutually Exclusive Category, you have to uncheck the checked part and then check the part you do want.

**Comment by DieForSly** [comment]
Here's the thing. Let's start from the start. I download the filter tool. Try it install it. First of all I can't click any buttons so I just press enter till it installs and stuff. But here's the problem when I do this everything installs. But when I install the filter tool and try to click on like for example "Developer tools" it just straight doesn't let me click it. Or any other things...

**Comment by DieForSly** [comment]
Sorry if it sounds a bit confusing it's just a weird problem I have. Tried searching this up but I couldn't find anything like this

**Comment by SommerXV** [comment]
I'd have no clue how to fix this, and not everyone checks the GitHub, I'd recommend joining Shadow's (creator of UCP) his Discord and ask about this in #patch-questions.

Discord Link: https://discordapp.com/invite/shadowevil

**Comment by CaptainKoby** [comment]
Closed, support has been given in the Discord
