### ISSUE TITLE
Trouble with skin to com

### ISSUE THREAD

**Issue by VaniPudding** [BLCM/BLCMods#885]
I tried to make the [Legendary Javelineer Com by Lftstrafe](https://github.com/BLCM/BLCMods/blob/f6100d2872205d60eb9cecea16cb2ce667da79c3/Borderlands%202%20mods/Lftstrafe/LegendaryJavelineer.txt) into a standalone com by replacing the bandit technical skin bloody eye instead of the legendary psycho com and adding it to the chubby lootpool using [Kazy's Tutorial](https://github.com/BLCM/BLCMods/blob/master/Borderlands%202%20mods/Kazy/Mods/ProjectS/Project%20Skin%20COM/Customization%20COMs) but i can't seem to make it work.
Please help.

`=====================
[BSE] BASE COMPONENTS
=====================
set GD_BanditTech_Items_MainGame.BanditTech.Skin_Blood ItemName Legendary Javelineer Class Mod

set GD_BanditTech_Items_MainGame.BanditTech.Skin_Blood CustomPresentations AttributePresentationDefinition 'GD_BanditTech_Items_MainGame.AttributePresentationDefinition_43'
set GD_BanditTech_Items_MainGame.AttributePresentationDefinition_43 Description "HOW DOES THIS THING WORK?" <br> <font color="#ffffff">Regenerates Rocket Launcher ammo.</font>
set GD_Lilac_ClassMods.Att_Presentations.AttrPresent_TasteOfBlood Description Nervous Blood Skill
set GD_Lilac_ClassMods.SkillGradeModifiers.TasteOfBlood:SkillAttributeContextResolver_0 AssociatedSkillPathName (PathComponentNames[3] = "GD_Lilac_Skills_Bloodlust",PathComponentNames[5] = "NervousBlood")
set GD_BanditTech_Items_MainGame.BanditTech.Skin_Blood AlphaParts GD_ClassMods.Specialization.Spec_Legendary

set GD_BanditTech_Items_MainGame.BanditTech.Skin_Blood OverrideMaterial MaterialInstanceConstant'Item_ClassMods.Mat.Mati_ClassMod_Psycho_Legendary'

set GD_BanditTech_Items_MainGame.BanditTech.Skin_Blood BaseRarity BaseValueConstant=5.000000,BaseValueAttribute=None,InitializationDefinition=None,BaseValueScaleConstant=1.000000)

set GD_BanditTech_Items_MainGame.BanditTech.Skin_Blood MonetaryValue (BaseValueConstant=0.000000,BaseValueAttribute=None,InitializationDefinition=AttributeInitializationDefinition'GD_Economy.PriceCalc.Init_ClassMods_Standard_PriceCalculator',BaseValueScaleConstant=1.000000)

set GD_BanditTech_Items_MainGame.BanditTech.Skin_Blood BaseMonetaryValueModifier 1.000000

set GD_BanditTech_Items_MainGame.BanditTech.Skin_Blood UIStatList((bDisplayAsModifierOnly=True,AttributeStyle=ATTRSTYLE_ModifierText,SupplementalAttributeStyle=ATTRSTYLE_JustNumber,StatCombinationMethod=SCM_Multiply,Attribute=AttributeDefinition'D_Attributes.DamageTypeModifers.InstigatedExplosiveDamageModifier',ConstraintAttribute=None,SupplementalAttributeExpression=(AttributeOperand1=None,ComparisonOperator=OPERATOR_EqualTo,Operand2Usage=OPERAND_PreferAttribute,AttributeOperand2=None,ConstantOperand2=0.000000),SupplementalAttributeToAppend=None),(bDisplayAsModifierOnly=True,AttributeStyle=ATTRSTYLE_ModifierText,SupplementalAttributeStyle=ATTRSTYLE_JustNumber,StatCombinationMethod=SCM_Multiply,Attribute=AttributeDefinition'D_Attributes.Weapon.WeaponClipSize',ConstraintAttribute=AttributeDefinition'D_Attributes.WeaponType.Weapon_Is_RocketLauncher',SupplementalAttributeExpression=(AttributeOperand1=None,ComparisonOperator=OPERATOR_EqualTo,Operand2Usage=OPERAND_PreferAttribute,AttributeOperand2=None,ConstantOperand2=0.000000),SupplementalAttributeToAppend=None),(bDisplayAsModifierOnly=True,AttributeStyle=ATTRSTYLE_ModifierText,SupplementalAttributeStyle=ATTRSTYLE_JustNumber,StatCombinationMethod=SCM_Multiply,Attribute=AttributeDefinition'D_Attributes.AmmoResource_Rocket_Launcher.Ammo_Rocket_Launcher_RegenerationRate',ConstraintAttribute=None,SupplementalAttributeExpression=(AttributeOperand1=None,ComparisonOperator=OPERATOR_EqualTo,Operand2Usage=OPERAND_PreferAttribute,AttributeOperand2=None,ConstantOperand2=0.000000),SupplementalAttributeToAppend=None))

set GD_BanditTech_Items_MainGame.BanditTech.Skin_Blood AttributeSlotEffects ((SlotName="PrimaryStatBonus",bExternalSlot=True,bRunEffectsAsSkill=False,AttributeToModify=AttributeDefinition'D_Attributes.DamageTypeModifers.InstigatedExplosiveDamageModifier',ConstraintAttribute=None,ModifierType=MT_PostAdd,BaseModifierValue=(BaseValueConstant=1.000000,BaseValueAttribute=None,InitializationDefinition=AttributeInitializationDefinition'GD_ClassMods.Misc.Init_StatBonus_Medium',BaseValueScaleConstant=0.420000),PerGradeUpgrade=(BaseValueConstant=0.100000,BaseValueAttribute=None,InitializationDefinition=None,BaseValueScaleConstant=0.100000),bIncludeInFunStats=False,bIncludeAlliesAsTarget=False,bEnforceMinimumGrade=False,bEnforceMaximumGrade=False,MinimumGrade=0,MaximumGrade=0,TargetInstanceDataName=),(SlotName="PrimaryStatBonus02",bExternalSlot=True,bRunEffectsAsSkill=True,AttributeToModify=AttributeDefinition'D_Attributes.Weapon.WeaponClipSize',ConstraintAttribute=AttributeDefinition'D_Attributes.WeaponType.Weapon_Is_RocketLauncher',ModifierType=MT_Scale,BaseModifierValue=(BaseValueConstant=1.000000,BaseValueAttribute=None,InitializationDefinition=AttributeInitializationDefinition'GD_ClassMods.Misc.Init_StatBonus_Weak',BaseValueScaleConstant=0.480000),PerGradeUpgrade=(BaseValueConstant=0.100000,BaseValueAttribute=None,InitializationDefinition=None,BaseValueScaleConstant=0.100000),bIncludeInFunStats=False,bIncludeAlliesAsTarget=False,bEnforceMinimumGrade=True,bEnforceMaximumGrade=False,MinimumGrade=0,MaximumGrade=0,TargetInstanceDataName=),(SlotName="StatPenalty",bExternalSlot=True,bRunEffectsAsSkill=True,AttributeToModify=AttributeDefinition'D_Attributes.AmmoResource_Rocket_Launcher.Ammo_Rocket_Launcher_RegenerationRate',ConstraintAttribute=None,ModifierType=MT_PostAdd,BaseModifierValue=(BaseValueConstant=1.000000,BaseValueAttribute=None,InitializationDefinition=AttributeInitializationDefinition'GD_ClassMods.Misc.Init_StatBonus_AmmoRegen',BaseValueScaleConstant=0.090000),PerGradeUpgrade=(BaseValueConstant=0.100000,BaseValueAttribute=None,InitializationDefinition=None,BaseValueScaleConstant=0.100000),bIncludeInFunStats=False,bIncludeAlliesAsTarget=True,bEnforceMinimumGrade=True,bEnforceMaximumGrade=False,MinimumGrade=0,MaximumGrade=0,TargetInstanceDataName=),(SlotName="Skill1",bExternalSlot=True,bRunEffectsAsSkill=True,AttributeToModify=InventoryAttributeDefinition'GD_Lilac_ClassMods.SkillGradeModifiers.BloodfilledGuns',ConstraintAttribute=None,ModifierType=MT_PostAdd,BaseModifierValue=(BaseValueConstant=0.000000,BaseValueAttribute=None,InitializationDefinition=AttributeInitializationDefinition'GD_ClassMods.Misc.Init_BaseSkillPointCalculation',BaseValueScaleConstant=1.000000),PerGradeUpgrade=(BaseValueConstant=0.340000,BaseValueAttribute=None,InitializationDefinition=None,BaseValueScaleConstant=1.000000),bIncludeInFunStats=True,bIncludeAlliesAsTarget=False,bEnforceMinimumGrade=True,bEnforceMaximumGrade=False,MinimumGrade=0,MaximumGrade=0,TargetInstanceDataName=),(SlotName="Skill2",bExternalSlot=True,bRunEffectsAsSkill=True,AttributeToModify=InventoryAttributeDefinition'GD_Lilac_ClassMods.SkillGradeModifiers.BloodBath',ConstraintAttribute=None,ModifierType=MT_PostAdd,BaseModifierValue=(BaseValueConstant=0.000000,BaseValueAttribute=None,InitializationDefinition=AttributeInitializationDefinition'GD_ClassMods.Misc.Init_BaseSkillPointCalculation',BaseValueScaleConstant=1.000000),PerGradeUpgrade=(BaseValueConstant=0.340000,BaseValueAttribute=None,InitializationDefinition=None,BaseValueScaleConstant=1.000000),bIncludeInFunStats=True,bIncludeAlliesAsTarget=False,bEnforceMinimumGrade=True,bEnforceMaximumGrade=False,MinimumGrade=0,MaximumGrade=0,TargetInstanceDataName=),(SlotName="Skill3",bExternalSlot=True,bRunEffectsAsSkill=True,AttributeToModify=InventoryAttributeDefinition'GD_Lilac_ClassMods.SkillGradeModifiers.FeedTheMeat',ConstraintAttribute=None,ModifierType=MT_PostAdd,BaseModifierValue=(BaseValueConstant=0.000000,BaseValueAttribute=None,InitializationDefinition=AttributeInitializationDefinition'GD_ClassMods.Misc.Init_BaseSkillPointCalculation',BaseValueScaleConstant=1.000000),PerGradeUpgrade=(BaseValueConstant=0.340000,BaseValueAttribute=None,InitializationDefinition=None,BaseValueScaleConstant=1.000000),bIncludeInFunStats=True,bIncludeAlliesAsTarget=False,bEnforceMinimumGrade=True,bEnforceMaximumGrade=False,MinimumGrade=0,MaximumGrade=0,TargetInstanceDataName=),(SlotName="Skill4",bExternalSlot=True,bRunEffectsAsSkill=True,AttributeToModify=InventoryAttributeDefinition'GD_Lilac_ClassMods.SkillGradeModifiers.StripTheFlesh',ConstraintAttribute=None,ModifierType=MT_PostAdd,BaseModifierValue=(BaseValueConstant=0.000000,BaseValueAttribute=None,InitializationDefinition=AttributeInitializationDefinition'GD_ClassMods.Misc.Init_BaseSkillPointCalculation',BaseValueScaleConstant=1.000000),PerGradeUpgrade=(BaseValueConstant=0.340000,BaseValueAttribute=None,InitializationDefinition=None,BaseValueScaleConstant=1.000000),bIncludeInFunStats=True,bIncludeAlliesAsTarget=False,bEnforceMinimumGrade=True,bEnforceMaximumGrade=False,MinimumGrade=0,MaximumGrade=0,TargetInstanceDataName=),(SlotName="Skill5",bExternalSlot=True,bRunEffectsAsSkill=True,AttributeToModify=InventoryAttributeDefinition'GD_Lilac_ClassMods.SkillGradeModifiers.TasteOfBlood',ConstraintAttribute=None,ModifierType=MT_PostAdd,BaseModifierValue=(BaseValueConstant=0.000000,BaseValueAttribute=None,InitializationDefinition=AttributeInitializationDefinition'GD_ClassMods.Misc.Init_BaseSkillPointCalculation',BaseValueScaleConstant=1.000000),PerGradeUpgrade=(BaseValueConstant=0.340000,BaseValueAttribute=None,InitializationDefinition=None,BaseValueScaleConstant=1.000000),bIncludeInFunStats=True,bIncludeAlliesAsTarget=False,bEnforceMinimumGrade=True,bEnforceMaximumGrade=False,MinimumGrade=0,MaximumGrade=0,TargetInstanceDataName=))

set GD_BanditTech_Items_MainGame.BanditTech.Skin_Blood AttributeSlotUpgrades ((SlotName="PrimaryStatBonus",GradeIncrease=0,bActivateSlot=True),(SlotName="PrimaryStatBonus02",GradeIncrease=0,bActivateSlot=True),(SlotName="Skill10",GradeIncrease=3,bActivateSlot=True),(SlotName="Skill11",GradeIncrease=3,bActivateSlot=True),(SlotName="Skill12",GradeIncrease=3,bActivateSlot=True),(SlotName="Skill13",GradeIncrease=3,bActivateSlot=True),(SlotName="Skill14",GradeIncrease=3,bActivateSlot=True))

===========================================
[S2C] SKIN TO COM SPECIFICS [DO NOT MODIFY]
===========================================
set GD_BanditTech_Items_MainGame.BanditTech.Skin_Blood DisplayClassModAtBeginningOfName 0
set GD_BanditTech_Items_MainGame.BanditTech.Skin_Blood OverridePool None
set GD_BanditTech_Items_MainGame.BanditTech.Skin_Blood CustomizationDef None
set GD_BanditTech_Items_MainGame.BanditTech.Skin_Blood CustomPresentations ()
set GD_BanditTech_Items_MainGame.BanditTech.Skin_Blood PrimaryColor (R=0.000000,G=0.000000,B=0.000000,A=0.000000)
set GD_BanditTech_Items_MainGame.BanditTech.Skin_Blood SecondaryColor (R=0.000000,G=0.000000,B=0.000000,A=0.000000)
set GD_BanditTech_Items_MainGame.BanditTech.Skin_Blood TertiaryColor (R=0.000000,G=0.000000,B=0.000000,A=0.000000)
set GD_BanditTech_Items_MainGame.BanditTech.Skin_Blood ItemCardTopStatString None
set GD_BanditTech_Items_MainGame.BanditTech.Skin_Blood bPlayerUseItemOnPickup None
set GD_BanditTech_Items_MainGame.BanditTech.Skin_Blood bUsesPlayerLevelRequirement True
set GD_BanditTech_Items_MainGame.BanditTech.Skin_Blood bAIUseItemOnPickup None
set GD_BanditTech_Items_MainGame.BanditTech.Skin_Blood bUseCoopRange None
set GD_BanditTech_Items_MainGame.BanditTech.Skin_Blood UsedStatId None
set GD_BanditTech_Items_MainGame.BanditTech.Skin_Blood DroppedImpact WillowImpactDefinition'GD_Impacts.Loot.Loot_Drop_Ammo'
set GD_BanditTech_Items_MainGame.BanditTech.Skin_Blood TitleList ("GD_ClassMods.Title.Title_ClassMod")
set GD_BanditTech_Items_MainGame.BanditTech.Skin_Blood PrefixList ()
set GD_BanditTech_Items_MainGame.BanditTech.Skin_Blood bItemNameIsFullName True
set GD_BanditTech_Items_MainGame.BanditTech.Skin_Blood NonCompositeStaticMesh None
set GD_BanditTech_Items_MainGame.BanditTech.Skin_Blood AlphaParts GD_ClassMods.Specialization.Spec_Legendary
set GD_BanditTech_Items_MainGame.BanditTech.Skin_Blood BetaParts ItemPartListDefinition'GD_ClassMods.StatPrimary.Z_PartsList_PrimaryStatParts'
set GD_BanditTech_Items_MainGame.BanditTech.Skin_Blood GammaParts ItemPartListDefinition'GD_ClassMods.StatPrimary02.Z_PartsList_PrimaryStat02Parts'
set GD_BanditTech_Items_MainGame.BanditTech.Skin_Blood MaterialParts ItemPartListDefinition'GD_ClassMods.StatPenalty.Z_PartsList_StatPenaltyParts'
set GD_BanditTech_Items_MainGame.BanditTech.Skin_Blood InventoryClass Class'WillowGame.WillowClassMod'
set GD_BanditTech_Items_MainGame.BanditTech.Skin_Blood bIsConsumable False
set GD_BanditTech_Items_MainGame.BanditTech.Skin_Blood PickupFlagIcon Texture2D'fx_shared_items.Textures.CommDeck_Dif'
set GD_BanditTech_Items_MainGame.BanditTech.Skin_Blood PickupSounds ((Event=AkEvent'Ake_Obj_Pickup.Obj_Pickup.Ak_Play_Obj_Pickup_Class_Mod',Cue=None,Expressions=))
set GD_BanditTech_Items_MainGame.BanditTech.Skin_Blood PlayerUseLevelBonus (BaseValueConstant=0.000000,BaseValueAttribute=None,InitializationDefinition=AttributeInitializationDefinition'GD_Balance_Inventory.LevelRequirement.Init_BaseGearLevelRequirementBonus',BaseValueScaleConstant=1.000000)
set GD_BanditTech_Items_MainGame.BanditTech.Skin_Blood Presentation InventoryCardPresentationDefinition'GD_InventoryPresentations.Definitions.CommDeck'
set GD_BanditTech_Items_MainGame.BanditTech.Skin_Blood Class Class'WillowGame.ClassModDefinition'
set GD_BanditTech_Items_MainGame.BanditTech.Skin_Blood ObjectArchetype ClassModDefinition'WillowGame.Default__ClassModDefinition'
set GD_BanditTech_Items_MainGame.BalanceDefs.BanditTech_Skin_Blood ClassModDefinitions ClassModDefinition'GD_BanditTech_Items_MainGame.BanditTech.Skin_Blood'
set GD_BanditTech_Items_MainGame.BalanceDefs.BanditTech_Skin_Blood ItemPartListDefinition'GD_ClassMods.StatPrimary.Z_PartsList_PrimaryStatParts'
set GD_BanditTech_Items_MainGame.BalanceDefs.BanditTech_Skin_Blood GammaParts ItemPartListDefinition'GD_ClassMods.StatPrimary02.Z_PartsList_PrimaryStat02Parts'
set GD_BanditTech_Items_MainGame.BalanceDefs.BanditTech_Skin_Blood MaterialParts ItemPartListDefinition'GD_ClassMods.StatPenalty.Z_PartsList_StatPenaltyParts'

======================================
[CHR] CHARACTER-SPECIFIC MODIFICATIONS
======================================
===============
Krieg COMs
===============
set GD_BanditTech_Items_MainGame.BalanceDefs.BanditTech_Skin_Blood ItemPartListCollection GD_Lilac_ClassMods.BalanceDefs.BalDef_ClassMod_Psycho_05_Legendary:PartList
set GD_BanditTech_Items_MainGame.BanditTech.Skin_Blood RequiredPlayerClass PlayerClassIdentifierDefinition'GD_LilacPackageDef.PlayerClassId.Psycho'
set GD_BanditTech_Items_MainGame.BanditTech.Skin_Blood UIMeshRotation (Pitch=2730,Yaw=14563,Roll=10012)
set GD_BanditTech_Items_MainGame.BanditTech.Skin_Blood PhysicsAsset PhysicsAsset'Lilac_Item_ClassMods.Meshes.Phat_PsychoClassMod'
set GD_BanditTech_Items_MainGame.BanditTech.Skin_Blood NonCompositeSkeletalMesh SkeletalMesh'Lilac_Item_ClassMods.Meshes.PsychoClassMod'

=========================================
[MFT] MANUFACTURER-SPECIFIC MODIFICATIONS
=========================================
================
Torgue
================
set GD_BanditTech_Items_MainGame.BanditTech.Skin_Blood ManufacturerOverride ManufacturerDefinition'GD_Manufacturers.Manufacturers.Torgue'
set GD_BanditTech_Items_MainGame.BalanceDefs.BanditTech_Skin_Blood Manufacturers ((Manufacturer=ManufacturerDefinition'GD_Manufacturers.Manufacturers.Torgue',Grades=((GradeModifiers=(ExpLevel=1,CustomInventoryDefinition=None),GameStageRequirement=(MinGameStage=0,MaxGameStage=100),MinSpawnProbabilityModifier=(BaseValueConstant=1.000000,BaseValueAttribute=None,InitializationDefinition=None,BaseValueScaleConstant=1.000000),MaxSpawnProbabilityModifier=(BaseValueConstant=1.000000,BaseValueAttribute=None,InitializationDefinition=None,BaseValueScaleConstant=1.000000)))))

======================
[DTI] DAMAGE TYPE ICON
======================
=========
EXPLOSIVE
=========
set GD_BanditTech_Items_MainGame.BanditTech.Skin_Blood DamageTypeIcon DAMAGE_TYPE_Explosive

=================================
[LOT] DROPPABLE LOCATION LOOTPOOL
=================================
set GD_Itempools.Runnables.Pool_ChubbieUniques BalancedItems ((ItmPoolDefinition=None,InvBalanceDefinition=WeaponBalanceDefinition'GD_Weap_Launchers.A_Weapons_Legendary.RL_Tediore_5_Bunny',Probability=(BaseValueConstant=0.000000,BaseValueAttribute=None,InitializationDefinition=AttributeInitializationDefinition'GD_Balance.Weighting.Weight_1_Common',BaseValueScaleConstant=1.000000),bDropOnDeath=True),(ItmPoolDefinition=None,InvBalanceDefinition=InventoryBalanceDefinition'GD_ItemGrades.Shields.ItemGrade_Gear_Shield_Booster_05_Legendary',Probability=(BaseValueConstant=0.000000,BaseValueAttribute=None,InitializationDefinition=AttributeInitializationDefinition'GD_Balance.Weighting.Weight_1_Common',BaseValueScaleConstant=1.000000),bDropOnDeath=True),(ItmPoolDefinition=KeyedItemPoolDefinition'GD_CustomItemPools_MainGame.Rewards.RedNinja',InvBalanceDefinition=None,Probability=(BaseValueConstant=0.000000,BaseValueAttribute=None,InitializationDefinition=AttributeInitializationDefinition'GD_Balance.Weighting.Weight_1_Common',BaseValueScaleConstant=1.000000),bDropOnDeath=True),(ItmPoolDefinition=None,InvBalanceDefinition=InventoryBalanceDefinition'GD_ItemGrades.Shields.ItemGrade_Gear_Shield_Standard_CrackedSash',Probability=(BaseValueConstant=0.000000,BaseValueAttribute=None,InitializationDefinition=AttributeInitializationDefinition'GD_Balance.Weighting.Weight_1_Common',BaseValueScaleConstant=1.000000),bDropOnDeath=True),(ItmPoolDefinition=ItemPoolDefinition'GD_Lobelia_Itempools.ClassModPools.Pool_ClassMod_Lobelia_All',InvBalanceDefinition=None,Probability=(BaseValueConstant=1600.000000,BaseValueAttribute=None,InitializationDefinition=None,BaseValueScaleConstant=1.000000),bDropOnDeath=True),(ItmPoolDefinition=None,InvBalanceDefinition=InventoryBalanceDefinition'GD_BanditTech_Items_MainGame.BanditTech.Skin_Blood',Probability=(BaseValueConstant=0.000000,BaseValueAttribute=None,InitializationDefinition=AttributeInitializationDefinition'GD_Balance.Weighting.Weight_1_Common',BaseValueScaleConstant=1.000000),bDropOnDeath=True))
// This adds the [place name here] Class Mod into [location]'s lootpool, while keeping [insert other drops here].
`

**Comment by SommerXV** [comment]
What exactly doesn't work, if I know that I can help you from there.

**Comment by VaniPudding** [comment]
well, it drops like a skin, it is green with only bonus Explosive Damage and Launcher Magazine Size, but no ammo regen and no skill boosts and it is level 1.

**Comment by VaniPudding** [comment]
![20180426233400_1](https://user-images.githubusercontent.com/38692706/39333275-9454f390-49aa-11e8-9990-155950642c34.jpg)


![20180426233348_1](https://user-images.githubusercontent.com/38692706/39333284-9ad834b6-49aa-11e8-9334-586fe265ed1d.jpg)
That is with the com equipt + it drops like a skin and not from chubbies.

**Comment by SommerXV** [comment]
1. You probably didn't gib in the correct parts, make sure you gib it in with the gamma parts etc like Sheep has (just copy like a... purple COM and add the Type & Balance from the skin onto it)
2. COM names will never show up on UI because it has no Prefix.
3. You may have messed up the array.
