### ISSUE TITLE
Issue editing torgue weapons 

### ISSUE THREAD

**Issue by NB55NB** [BLCM/BLCMods#912]
I am editing the body of blue and white torgue weapons and the fire interval effect which I have used only dozens of other weapons is not working for torgue weapons. Any ideas why?

**Comment by apocalyptech** [comment]
Hey there, gonna close out this ancient Issue - if you're still looking to accomplish this, it'd be best to just stop by the Discord.  As you can tell, the Issues here don't tend to get looked at too often.
