### ISSUE TITLE
Reborn not deploying on one character

### ISSUE THREAD

**Issue by wheeldogz** [BLCM/BLCMods#917]
I have been using BL2Reborn for a week with no issues. I have been using it on two toons... UVHM Gaige and TVHM Axton. Today, Reborn would not deploy for Axton but will for Gaige. However, the regular community patch will work for Axton. Just not BL2Reborn. I have left everything checked, nothing unchecked that is. Does anyone know how I can troubleshoot? Windows 10 64 bit

**Comment by NB55NB** [comment]
Is it spark 6 configuration? Or is nothing showing up at the main menu and on the character?

**Comment by wheeldogz** [comment]
Well that's a good question, but why would it impact Axton only... It's
very curious. My next move is to delete the toon and make a new one and see
if I can pinpoint it after starting from scratch. I'll let you know if I
figure it out. Thank you for your time. I love this mod /patch.

**Comment by NB55NB** [comment]
No problem! Good luck!
