### ISSUE TITLE
weapon replacements?

### ISSUE THREAD

**Issue by virtusinsania** [BLCM/BLCMods#918]
I aquired the striker, sledge's, and edge but none of them would change, why?

**Comment by NB55NB** [comment]
What file are you using to change them?

**Comment by virtusinsania** [comment]
the filter tool or do I need to download the guns separate?

**Comment by NB55NB** [comment]
I'm guessing you are using the Patch for the Pre-Sequel have you checked the boxes in the filter tool for optional replacements?

**Comment by virtusinsania** [comment]
in the custom section of the filter tools it says you can change these guns to different, yes but when I start the game up they are the same

**Comment by NB55NB** [comment]
Did you save the file after checking the boxes?

**Comment by virtusinsania** [comment]
I click both save patch and save to file selecting the patch

**Comment by virtusinsania** [comment]
well redownloaded twice and didn't work either time, it says everything is hex edited correctly. I guess it just won't work for me.

**Comment by virtusinsania** [comment]
everything else is working in the patch

**Comment by virtusinsania** [comment]
scratch that nisha's action skill still has the old visual effect I don't think 2.1 is working at all

**Comment by apocalyptech** [comment]
Closing this one out -- if you're still having problems with this, please stop by the Discord, where you'll have a much better chance of getting timely help!
