### ISSUE TITLE
Reborn - No fridge fast travel

### ISSUE THREAD

**Issue by firef1end** [BLCM/BLCMods#920]
I've noticed on my Normal Mode playthrough as Gaige that the fridge is not available for fast travel; even when using the exact station it does not appear on the list. Any fixes or ways to counteract this?
I am solely running the latest Reborn patch and no other mods.

**Comment by CaptainKoby** [comment]
Is not a Reborn or mod issue, it's a vanilla issue. 

Workaround is actually going into the Fridge (past the door you open at the beginning), then back to the Fast Travel and then activate it. Same happens in Caustic Caverns.
