### ISSUE TITLE
Unable to import mods into Filter Tool

### ISSUE THREAD

**Issue by RogerWilc0** [BLCM/BLCMods#923]
Attempting to import mods from folder created by Filter Tool. Both the filter tool.exe and the mods folder are in the binary folder. When I try to load a mods folder, the client reports the attached error and says to contact the administrator before shutting down. 

[log-1525952251591.txt](https://github.com/BLCM/BLCMods/files/1991587/log-1525952251591.txt)

**Comment by CaptainKoby** [comment]
Importing from mods folder is a bit bugged, use the "Add single mod" option. It's much more stable.

Pro tip: You can actually select multiple mods when using that option.
