### ISSUE TITLE
Changing Action Skill Base Cooldown

### ISSUE THREAD

**Issue by NoahKr** [BLCM/BLCMods#937]
Does anyone know of a way to alter the base cooldown of an action skill?
I know it can be done as the borderlands 2.5 modpack does it.

For clarification I'm not talking about Cooldown Reduction Rate. I'm talking about the actual base cooldown duraton. (42 for salvador for instance)

Thanks in advance :)

**Comment by WubTheGame** [comment]
Try comparing the code between Vanilla (In FilterTool) and BL2.5.

**Comment by NoahKr** [comment]
I believe the Borderlands 2.5 code isn't publicly available. I already tried searching for it without any luck.

**Comment by NoahKr** [comment]
I already figured out how to do it. To change zero's cooldown:

`set GD_Assassin_Skills.Misc.Cooldown_Deception:ConstantAttributeValueResolver_0 ConstantValue 36.000000`

A list of all attributes (including the other characters action skill cooldown) can be found here https://github.com/BLCM/BLCMods/blob/24327c99152b5756f1453d80671aba0c1f02bc57/Borderlands%202%20mods/Dave/Resources/RESOURCE%20-%20WEAPONS%20ATTRIBUTES.txt

**Comment by WubTheGame** [comment]
Neat. That could be useful for me in the future.
