### ISSUE TITLE
Preventing the use of weapons during an action skill

### ISSUE THREAD

**Issue by NoahKr** [BLCM/BLCMods#940]
Hi I was wondering if anyone knows if it's possible to prevent the use of weapons during an action skill.
Krieg's Buzzaxe Rampage prevents him from using guns.

I believe the following two lines in his ActionSkillArchetype cause that:
`ActiveWeaponSlot=0`
`bAllowNonBuzzaxeEquip=False`

Now let's say I would like to add such a restriction to Zer0's Decepti0n. Would that be possible? To allow Zer0 to only use melee during it's action skill?

**Comment by WubTheGame** [comment]
I see no reason why not. Give it a try.

**Comment by WubTheGame** [comment]
I see no reason why not. Give it a try.

**Comment by NoahKr** [comment]
How would I do that? I only have experience modifying skill attributes, not archetypes.

**Comment by WubTheGame** [comment]
Sorry, i didn't realize. Anyway, it should be doable, though i'm not entirely sure how if i can't just place the ```ActiveWeaponSlot=0``` into a set command for a character's skill code. I might see what i can do.

**Comment by NoahKr** [comment]
Do you have an example of the syntax of the set command? I haven't used it before.

**Comment by WubTheGame** [comment]
```set GD_Lilac_SkillsBase.ActionSkill.Skill_Psycho ActiveWeaponSlot 0``` Or something, maybe. But with Zer0's Action Skill definition.

**Comment by Akathris** [comment]
I would assume you have to hotfix that using Filter Tool btw

**Comment by Akathris** [comment]
Since skill changes have to be hotfixed

**Comment by WubTheGame** [comment]
Yeah, that's likely to be the case.

**Comment by NoahKr** [comment]
For anyone wondering. I tried it but it doesn't work. It think that's an attribute only related to Krieg's actionskill archetype.

**Comment by NoahKr** [comment]
After some more attempt I ended up with two 'solutions':

1) reduce the mag size to zero. This however requires a reload after the action skill and can be quite annoying.

2) reduce projectile amount and shooting cost to 0. So you effectively shoot blanks.

**Comment by WubTheGame** [comment]
Well, It's better than nothing, ain't it?

**Comment by NoahKr** [comment]
Definitely.

**Comment by apocalyptech** [comment]
Going to close this out, btw!  The Issues section here has never been terribly-well monitored; you've had one of the luckier ones where you've actually gotten some responses.  We're actually just about to close the Issues section entirely, so for future questions (or for more input on this issue), you'll want to hop into the Discord and ask about it there, instead!
