### ISSUE TITLE
:request: No more multiple bullet consumption on weapons

### ISSUE THREAD

**Issue by JustinCazzer** [BLCM/BLCMods#944]
Hi hi :) Justin here.

I do apologize if this isnt the correct area to request mods, Im just new to Github haha.

So as the title somewhat says in a nutshell, I'm wondering if anyone is able to create a mod which makes all weapons such and quads etechs and all the rest to only consume 1 bullet per shot. I am aware of how tedious this request might be so i wont really mind if its to much. :)

Thank you in advance.

**Comment by WubTheGame** [comment]
It'd probably have to be a fairly large mod, because you'd have to edit code for A LOT of guns in the game. It IS possible, though.

**Comment by JustinCazzer** [comment]
Thank you very much my good sir my friend and i will use this with great joy :D
