### ISSUE TITLE
Cant download 

### ISSUE THREAD

**Issue by Chinfu1189** [BLCM/BLCMods#948]
For some reason everytime i try to download the CEClassRandomizer i keep getting sent to a new tab and not given a download button or it never starts downloading

**Comment by FromDarkHell** [comment]
https://www.dropbox.com/s/7nehx9h23doak0t/CERandomizer.txt?dl=0 Click the "Direct Download" button

**Comment by WubTheGame** [comment]
Also, instead of downloading, you can click "Raw" and copy paste all the text into a .txt file.
