### ISSUE TITLE
wont even let me download it

### ISSUE THREAD

**Issue by slothyboi2** [BLCM/BLCMods#957]

**Comment by Ethel173** [comment]
need more info, cant download what, from where, and how are you trying?

**Comment by Sansibar1234** [comment]
i guess he means that if you hit the download button, it sends you to the text instead the downloadable file

**Comment by pootismannsdispenser** [comment]
thats the same issue with me

**Comment by pootismannsdispenser** [comment]
trying to open it only took me directly to the raw data, with no installation.

**Comment by pootismannsdispenser** [comment]
I have found a way to circumvent this issue, going directly into the raw in its own tab on firefox and using "Save page as" seems to work just fine.
