### ISSUE TITLE
BL2 Class Randomizer Mod cant be downloaded

### ISSUE THREAD

**Issue by Matt90765** [BLCM/BLCMods#958]

**Comment by FromDarkHell** [comment]
https://www.dropbox.com/s/7nehx9h23doak0t/CERandomizer.txt?dl=0 Click the "Direct Download" button

Unless you mean FromDarkHell's Class Mod Randomizer in which case:
you can click "Raw" and copy paste all the text into a .txt file.
The previously mentioned method works on all mods.
