### ISSUE TITLE
Wont load 

### ISSUE THREAD

**Issue by thegod7050** [BLCM/BLCMods#959]
i dont whats wrong  but it wont load into game when i try to run this one but all the others work

**Comment by thegod7050** [comment]
the Random enemy wont work

**Comment by FromDarkHell** [comment]
- Very first thing, make sure other mods work which include hotfixes (eg. UCP, make sure you're connected to Steam / SHiFT etc etc)
- MERGE THE ENEMY RANDOMIZER WITH ANY MODS YOU USE. The Enemy Randomizer uses hotfixes and you can't execute one mod with hotfixes after another with hotfixes, they need to be merged with the Filter Tool
     - Open the Filter Tool.
      - In the navigation bar, select "File" and "Open file" and pick the mod.
      - Once the mod is opened in the Filter Tool, click on "Developer Tools" and choose "Add single mod".
      - Pick the mod you want to add and done.
             - If you want to change the load order, click "Developer Tools" and choose "Enable structural edits", then drag the mod where you want it to be. Mods lower in the load order will overwrite mods higher in the load order.
- If it still doesn't work, **make sure you have all story DLCs and UVHM Pack 2 (Digistruct Peak). You also need the Headhunter Packs OR disable them in the Enemy Randomizer with the Filter Tool** (see here: https://i.imgur.com/i2mPHym.png)

Final notes: Enemy Randomizer requires a mid-good PC cause it loads every map in the game at once. It also most likely does not work with cracked Borderlands 2 versions.

**Comment by thegod7050** [comment]
do u need the UVHM pack 2 also thankyou
