### ISSUE TITLE
How to update existing files

### ISSUE THREAD

**Issue by villlads** [BLCM/BLCMods#963]
I`m new to Github and its mechanics so could someone tell me how to update the files i have in the Borderlands 2 tap

**Comment by Ethel173** [comment]
delete file
add updated file

**Comment by villlads** [comment]
but i can see in the history that they "update" there files and not "deletet ___ Added ____"

**Comment by apocalyptech** [comment]
The folks "updating" might be using local git checkouts/clones on their local machines, which gives you a *lot* more flexibility than the web UI does.  You can try it out yourself with Github Desktop, or any variety of other frontends, though note that you may be a bit on your own in terms of support for that.  The web UI might only really allow you to delete/add.

Anyway, closing this out!
