### ISSUE TITLE
Load Loop When creating a new game

### ISSUE THREAD

**Issue by Deltasquad16** [BLCM/BLCMods#969]
Hello, I am new to the BL2 modding community and i saw this mod and thought it would be fun to try. I downloaded this file, stuck it in binaries with the community patch and the hex editor tool, and i booted it up and executed the file but when i began a new game it would load for hours. I troubleshooted it to death but still have had no luck. Please help!

**Comment by WubTheGame** [comment]
No one can help you unless you specifically state the name of the mod you're using. It should be in Filtertool. just type it here.

**Comment by Deltasquad16** [comment]
Sorry new to github too https://github.com/BLCM/BLCMods/blob/master/Borderlands%202%20mods/LightChaosman/Enemy_Randomizer.txt

Also i found a way to get past the infinite load loop by executing it after i enter a game but then the enemies never see me even if i shoot them. They just casually stroll around.

**Comment by WubTheGame** [comment]
https://discord.gg/shadowevil Go here on Discord and read the faq-read-me-before-asking channel. If that does not fix your issue, use the Patch Troubleshooting channel.

**Comment by Ethel173** [comment]
https://github.com/BLCM/BLCMods/wiki/Randomizer-FaQ
