### ISSUE TITLE
slag chain lightning

### ISSUE THREAD

**Issue by dtbartlett** [BLCM/BLCMods#977]
I wanted to try and make the chain lightning into a slag version.  I only managed to remove the element without replacing it. I used the grenade unlocker text, but I'm pretty new. Just been copy pasting to make ends meet so far.
edit: Fixed the slag portion. I forgot a parenthesis haha. updated file. Still can't figure out if its possible to add another damage type for grenades.
[Dark Lightning.txt](https://github.com/BLCM/BLCMods/files/2096183/Dark.Lightning.txt)

**Comment by dtbartlett** [comment]
Also, is there a way to add a shock damage on impact to maintain a lightning theme and help with grenade damage?

**Comment by apocalyptech** [comment]
Hello!  If you're still having a problem with this, and it's something you'd like fixed, it'd probably be best to head over to the Discord to ask about it.  As you've probably noticed, this "Issues" area on the github isn't very well monitored.  You'll get some much quicker answers over there.
