### ISSUE TITLE
Problem with the enemy randomizer

### ISSUE THREAD

**Issue by melonjelly** [BLCM/BLCMods#980]
cant actually access the options to disable the headhunter pack and all i see is code on the filtertool
![screenshot_1](https://user-images.githubusercontent.com/40216078/41314361-3f65e848-6e95-11e8-8925-dfeff174f333.png)

**Comment by FromDarkHell** [comment]
When downloading a mod, click on the link itself and then click _**Raw**_ then do "Save As" after right-clicking.
