### ISSUE TITLE
Enemy Randomizer

### ISSUE THREAD

**Issue by Highrize** [BLCM/BLCMods#983]
Hello. I've recently seen youtuber 'Ki11er Six' and he did a video on your enemy randomizer as well as fromdarkhell's gun randomizer. I've followed his steps exactly, and I got the other mods to work, but not the enemy randomizer one. I'm very new to all of this, so sorry if the solution is simple. Your mod shows up inside the filter tool, and in my binaries and my borderlands 2 folders. I've tried many different things to get it to work without any progress. I have all of the headhunters and everything, the mod just will not work. Thank you for taking the time to read this, and I would appreciate any tips you could give me to help make borderlands 2 fun again after 3500+ hours. Not sure if i have to do something special to execute it or something.  Also, if you look at the comments of the video, many people are having the same issue as me.

**Comment by apocalyptech** [comment]
Hello, if you're still having this problem on BLCMM, I'd recommend hopping into the Discord to ask about it there.  This "Issues" area on github isn't really well monitored, and questions like yours can end up sitting around for ages (as you've doubtless noticed).  Anyway, BLCMM's come out in the meantime, which may help, and the FAQ at the Discord has some stuff specifically about the randomizers, so hop on over there if it's still being problematic.

Closing this out!
