### ISSUE TITLE
TPS UCP removes equipped weapon+shield from out-of-suit Flame Knuckle

### ISSUE THREAD

**Issue by apocalyptech** [BLCM/BLCMods#985]
Mostly just leaving this here for my own tracking, but TPS UCP does what it says in the title.  The issue is the `Fixed FlameKnucle to Drop Nukem On Normal mode` section (in 2.0), which sets `PlayThroughs[0].CustomItemPoolList`.  That completely overrides the object's `DefaultItemPoolList` and just replaces it with the Nukem drop, which means that everything else in the default pool is ignored.  (Including his shield + weapon).

**Comment by Ravenjim** [comment]
noted.

**Comment by apocalyptech** [comment]
Closing this out!  Will just track in Discord.
