### ISSUE TITLE
UCP Filter tool out of memory error

### ISSUE THREAD

**Issue by ManJamInYourHands** [BLCM/BLCMods#994]
I used the filter tool to combine mods without fail usually but if I try to combine BL2Reborn and pandamonium via "add single mod" and then try to save the file it fails with an out of memory error. I even use the command line to increase the heap size to 2gb and it still failed.

[log-1529186963034.txt](https://github.com/BLCM/BLCMods/files/2108550/log-1529186963034.txt)

**Comment by apocalyptech** [comment]
Hey there, if this is still happening, could you just join the Discord and ask in there?  I'm afraid this "Issues" tab isn't really kept up very well; we're considering closing it down altogether.  I'll close this one out for now.
