### ISSUE TITLE
FFYL/ New Game/ Selecting Gage the Mechromancer

### ISSUE THREAD

**Issue by IC-Prey** [BLCM/BLCMods#995]
I just reinstalled Borderlands 2 to try you this mod because it seems intresting but each time i try to pick the mechromancer the game stops responding? I have not installed the mod properly?

**Comment by IC-Prey** [comment]
also it seems to only happen with the gage. I can switch between all of the other characters but her.

**Comment by IC-Prey** [comment]
Just tested if there was an issue continuing a new game with Gage and it seems to not crash.......

**Comment by WubTheGame** [comment]
https://discord.gg/shadowevil Go here for help and explain your issue.

**Comment by apocalyptech** [comment]
Closing this out - as Wub suggested, heading to the Discord is probably your best bet here, if it's still an issue for you.
